(ch:array-oriented)=
# 어레이 중심 프로그래밍

**어레이 중심 프로그래밍**<font size='2'>array-oriented programming</font>은
목적에 맞는 어레이 생성을 위해 주어진 어레이를 효율적으로 활용하는 일에 집중함을 의미한다.
여기서는 어레이 중심 프로그래밍에 가장 중요한 넘파이 함수와 어레이 메서드를 소개한다.

**기초 라이브러리**

In [1]:
import numpy as np

**데이터셋 저장소**

In [2]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

## 기초 통계 메서드

### 합, 평균, 표준편차

넘파이 어레이에 사용된 항목들의 합, 평균값, 표준편차 등 기본 통계를 계산하는 어레이 메서드가 지원된다.
활용법을 보여주기 위해 아래 `(2, 3)` 모양의 어레이를 활용한다.

In [3]:
arr = np.arange(1, 7).reshape(2, 3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

**`sum()` 메서드**

어레이에 포함된 모든 값들의 합을 계산한다.

In [7]:
arr.sum()

np.int64(21)

**`mean()` 메서드**

어레이에 포함된 모든 값들의 평균값을 계산한다.

In [8]:
arr.mean()

np.float64(3.5)

**`std()` 메서드**

어레이에 포함된 모든 값들의 표준편차 계산한다.

In [9]:
arr.std()

np.float64(1.707825127659933)

### 축 활용

앞서 언급된 모든 메서드는 축<font size='2'>axis</font>을 이용하는 옵션도 지원한다.
축 지정은 `axis` 매개변수의 키워드 인자를 활용한다.

* `axis=0`: 열별로 메서드 적용. 1차원 어레이 반환.
* `axis=1`: 행별로 메서드 적용. 1차원 어레이 반환.

<div align="center">
    <img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/ufunc-sum.png" width="330">
</div>

<div style="text-align: center">&lt;그림 출처: <a href="https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d">NumPy Illustrated: The Visual Guide to NumPy</a>&gt;</div>

**열별 합**

In [12]:
arr.sum(axis=0)

array([5, 7, 9])

**행별 합**

In [13]:
arr.sum(axis=1)

array([ 6, 15])

**열별 평균값**

In [14]:
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

**행별 평균값**

In [15]:
arr.mean(axis=1)

array([2., 5.])

**열별 표준편차**

In [16]:
arr.std(axis=0)

array([1.5, 1.5, 1.5])

**행별 표준편차**

In [17]:
arr.std(axis=1)

array([0.81649658, 0.81649658])

### `min()` vs. `argmin()`

설명을 위해 아래 어레이를 이용한다.

In [18]:
arr= np.array([[4, 8, 5], [9, 3, 1]])
arr

array([[4, 8, 5],
       [9, 3, 1]])

**`min()` 메서드**

어레이에 포함된 항목 중에서 최솟값을 반환한다.
축을 활용하면 열별, 행별 최솟값을 포함한 1차원 어레이가 반환된다.

<div align="center">
    <img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/ufunc-min.png" width="350px">
</div>

<div style="text-align: center">&lt;그림 출처: <a href="https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d">NumPy Illustrated: The Visual Guide to NumPy</a>&gt;</div>

In [19]:
arr.min()

np.int64(1)

In [24]:
arr.min(axis=0)

array([4, 3, 1])

In [25]:
arr.min(axis=1)

array([4, 1])

**`max()` 메서드**

어레이에 포함된 항목 중에서 최댓값을 반환한다.
축을 활용하면 열별, 행별 최댓값을 포함한 1차원 어레이가 반환된다.

In [20]:
arr.max()

np.int64(9)

In [26]:
arr.max(axis=0)

array([9, 8, 5])

In [27]:
arr.max(axis=1)

array([8, 9])

**`argmin()` 메서드**

어레이에 포함된 항목 중에서 최솟값이 위치한 곳의 인덱스를 반환한다.
반환값은 정수 인덱스이며, 상단 왼편부터 0, 1, 2, 등으로 인덱스를 정한다.
축을 활용하면 열별, 행별 최솟값이 위치한 곳의 인덱스로 구성된 1차원 어레이가 반환된다.

In [31]:
arr.argmin()

np.int64(5)

In [32]:
arr.argmin(axis=0)

array([0, 1, 1])

In [33]:
arr.argmin(axis=1)

array([0, 2])

<div align="center">
    <img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/ufunc-argmin.png" width="350px">
</div>

<div style="text-align: center">&lt;그림 출처: <a href="https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d">NumPy Illustrated: The Visual Guide to NumPy</a>&gt;</div>

**`argmax()` 메서드**

어레이에 포함된 항목 중에서 최댓값이 위치한 곳의 인덱스를 반환한다.
반환값은 정수 인덱스이며, 상단 왼편부터 0, 1, 2, 등으로 인덱스를 정한다.
축을 활용하면 열별, 행별 최솟값이 위치한 곳의 인덱스로 구성된 1차원 어레이가 반환된다.

In [35]:
arr.argmax()

np.int64(3)

In [36]:
arr.argmax(axis=0)

array([1, 0, 0])

In [37]:
arr.argmax(axis=1)

array([1, 0])

## 부울 인덱싱

어레이를 이용한 논리식 또한 항목별로 작동하여
부울 어레이가 생성된다.

In [44]:
arr2 = np.arange(1, 7).reshape(2, 3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

아래 논리식은 각각의 항목에 대해 5보다 큰지 여부를 판단한다.

In [45]:
arr2 > 5

array([[False, False, False],
       [False, False,  True]])

**np.any() 함수**

한 개 이상의 어레이 항목이 참인지 여부를 판단하며, 축을 기준으로 참, 거짓 여부를 판단할 수도 있다.

<div align="center"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/ufunc-any.png" style="width:400px;"></div>

<p><div style="text-align: center">&lt;그림 출처: <a href="https://betterprogramming.pub/numpy-illustrated-the-visual-guide-to-numpy-3b1d4976de1d">NumPy Illustrated: The Visual Guide to NumPy</a>&gt;</div></p>

In [46]:
np.any(arr2 > 5)

True

In [47]:
np.any(arr2 > 5, axis=0)

array([False, False,  True])

In [48]:
np.any(arr2 > 5, axis=1)

array([False,  True])

**np.all() 함수**

어레이의 모든 항목이 참인지 여부를 판단하며, 축을 기준으로 참, 거짓 여부를 판단할 수도 있다.

In [49]:
np.all(arr2 > 5)

False

In [50]:
np.all(arr2 > 5, axis=0)

array([False, False, False])

In [51]:
np.all(arr2 > 5, axis=1)

array([False, False])

**`any()`/`all()` 메서드**

`np.any()`/`np.all()` 함수 대신에 `any()`/`all()` 메서드를 활용할 수도 있다.

아래 코드는 모든 항목이 짝수인지 여부를 판단한다.

In [52]:
(arr2 % 2 == 0).all()

False

짝수가 하나라도 있는지를 알고 싶으면 `any()`를 사용한다.

In [53]:
(arr2 % 2 == 0).any()

True

축 별로 확인할 수도 있다.

In [54]:
(arr2 % 2 == 0).all(axis=0)

array([False, False, False])

In [55]:
(arr2 % 2 == 0).all(axis=1)

array([False, False])

In [56]:
(arr2 % 2 == 0).any(axis=0)

array([ True,  True,  True])

In [57]:
(arr2 % 2 == 0).any(axis=1)

array([ True,  True])

**참인 항목의 개수: `sum()` 메서드 활용**

`sum()` 메서드를 이용하여 특정 조건을 만족하는 항목들의 개수를 확인할 수 있다.
이유는 `True`는 1, `False`는 0으로 간주되기 때문이다.
아래 코드는 1부터 6까지의 정수 중에서 짝수가 3개임을 확인해준다.

In [58]:
(arr2 % 2 == 0).sum()

3

## 연습문제

참고: [(실습) 어레이 중심 프로그래밍](https://colab.research.google.com/github/codingalzi/datapy/blob/master/practices/practice-numpy_3.ipynb)