(ch-numpy-array)=
# 넘파이 어레이

넘파이<font size='2'>numpy</font>는 NUMerical PYthon의 줄임말이며,
파이썬 데이터 사이언스에서 가장 유용하게 활용되는 도구를 제공하는 라이브러리다.
넘파이가 제공하는 핵심 요소는 효율적으로 데이터를 저장하고 관리하는 1차원, 2차원, 3차원 등 다차원 어레이(배열)와
메모리 효율적이며 빠른 어레이 연산이다.

`numpy` 라이브러리는 관습적으로 별칭 `np`로 불러온다.

In [2]:
import numpy as np

## 다차원 어레이

넘파이 어레이는 리스트 자료형처럼 많은 데이터를 하나의 객체로 묶어 다루는 모음 자료형이며,
데이터 분석, 머신러닝, 딥러닝 등 다량의 데이터로 구성된 데이터셋을
처리할 때 일반적으로 활용된다.
아래 표에 리스트와 넘파이 어레이의 차이점을 정리하였다.

| 요소 | 리스트 | 넘파이 어레이 |
|------|--------|---------------|
| 데이터 저장 | 데이터 모음 | 데이터 모음 |
| 객체 속성 | 항목 저정 이외에 기타 속성 없음. | 값과 함께 데이터 저장 형식의 모양, 차원, 항목 자료형 등 객체의 메타 데이터를 속성으로 저장 |
| 메서드 | 기본 메서드 제공 | 데이터 과학에 유용한 많은 메서드 제공 |
| 자료형 제약 | 서로 다른 자료형 혼용 가능 | 모든 항목이 동일한 자료형으로 통일되어야 함 |
| 차원 | 차원 개념 없지만 중첩 리스트 지원 | 1차원, 2차원, 3차원, 4차원 등 다차원 구조 지원 |

여기서는 가장 많이 활용되는 1차원과 2차원 어레이의 사용법을 소개한다.

### 1차원 어레이

1차원 어레이는 중첩이 없는 리스트와 동일한 모양을 가지며, 리스트에 `np.array()` 함수를 적용하여 생성할 수 있다.
1차원 어레이는 **벡터**<font size='2'>vector</font>로도 불린다.

In [3]:
list_1D = [1, 17, -7.5, 3.14, 2.71828]
arr_1D = np.array(list_1D)

`arr_1D`는 `list_1D` 변수가 가리키는 리스트와 동일한 항목을 갖는 1차원 어레이를 가리킨다.

In [4]:
arr_1D

array([ 1.     , 17.     , -7.5    ,  3.14   ,  2.71828])

**항목 자료형**

리스트의 경우 임의의 자료형이 섞인 항목들을 가질 수 있지만
어레이는 항목들의 통일된 자료형을 요구한다.
따라서 위 출력 결과를 보면 `1`과 `17`이 각각 `1.`과 `17.` 변환되어 모든 항목이 부동소수점으로 구성되었다.
`1.`과 `17.`은 각각 `1.0`과 `17.0`을 가리킨다.
어레이 항목들의 통일된 자료형은 어레이 객체의 `dtype` 속성으로 확인된다.

In [5]:
arr_1D.dtype

dtype('float64')

**축**

1차원 어레이의 항목은 리스트처럼 왼쪽에서부터 오른쪽으로 하나의 방향으로만 이동하면서 확인할 수 있다.
이런 의미에서 1차원 어레이는 한 개의 **축**<font size='2'>axis</font>을 갖는다고 말한다.

**인덱스**

각 항목은 왼쪽에서부터 차례대로 0, 1, 2, ... 로 시작하는 **인덱스**를 갖는다.
예를 들어, `arr_1D`이 가리키는 1차원 어레이에 포함된 `-7.5`의 인덱스는 2다.

**차원**

어레이 자신의 차원은 `ndim` 속성에 할당되어 있다.

In [6]:
arr_1D.ndim

1

**모양**

어레이는 자신의 모양을 `shape` 속성에 튜플 자료형으로 저장한다.
1차원 어레이의 모양은 길이가 1인 튜플이며, 튜플의 유일한 항목은 1차원 어레이에 포함된 항목의 개수다.
`arr_1D`가 가리키는 1차원 어레이는 5개의 항목을 포함하기에 
모양은 `(5,)`이다.

In [7]:
arr_1D.shape

(5,)

:::{note} 쉼표의 중요성

길이가 1인 튜플은 `(5,)`처럼 반드시 쉼표가 포함되어 있음에 주의한다.
반면에 `(5)`는 그냥 정수 `5`와 동일하다. 즉, 튜플이 아닌 `int` 자료형이다.
:::

**어레이 객체 자료형**

넘파이 어레이 객체의 자료형은 항목 자료형, 차원, 모양과 상관없이 항상 `numpy.ndarray`다.
자료형은 `type()` 함수를 이용하여 확인한다.

In [8]:
type(arr_1D)

numpy.ndarray

### `np.arange()` 함수

`np.arange()` 함수는 `range()` 함수와 매우 유사한 기능을 갖지만, 리스트가 아닌 넘파이 어레이를 반환한다.
예를 들어, 아래 코드는 0부터 9 사이의 정수로 구성된 1차원 어레이를 생성한다.

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`range()` 함수와는 다르게 부동소수점을 스텝으로 사용할 수도 있으며,
그러면 부동소수점으로 구성된 1차원 어레이가 생성된다.
예를 들어, 아래 코드는 0부터 시작해서 스텝 0.1씩 증가시키면서 생성되는 값들로 구성된 1차원 어레이를 생성한다.
단, 오른쪽 끝값인 1 이전까지 스텝을 반복 적용한다.

In [10]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### 2차원 어레이

2차원 어레이의 모든 항목은 동일한 모양의 1차원 어레이어야 한다.
따라서 동일한 길이의 리스트를 항목으로 갖는 중첩 리스트를 2차원 어레이로 변환할 수 있다.
아래 코드는 길이가 4인 세 개의 리스트를 항목으로 갖는 중첩 리스트 `list_2D`를 2차원 어레이 `arr_2D`로 변환한다.

In [11]:
list_2D = [[1, 2, 3, 4],
           [5, 6, 7, 8],
           [9, 10, 11, 12]]
arr_2D = np.array(list_2D)

arr_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**축과 행렬**

2차원 어레이는 **행**<font size='2'>row</font>과 **열**<font size='2'>column</font>
두 개의 축을 가지며, 행은 0번 축, 열은 1번 축이라 부르기도 한다. 
행과 열을 갖는다는 의미에서 **행렬**<font size='2'>matrix</font>로 불린다.
예를 들어, `arr_2D`는 3개의 행과 4개의 열을 갖는 아래 모양의 행렬에 대응한다.

$$
\begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8\\
9 & 10 & 11 & 12
\end{bmatrix}
$$

**행과 열 인덱스**

인덱스는 축별로 지정된다.
위 2차원 어레이의 경우 3개의 행에 대해 맨 위 행부터 차례대로 0, 1, 2 행 인덱스가,
4개의 열에 대해 맨 왼쪽 열부터 차례대로 0, 1, 2, 3 열 인덱스가 지정된다.
2차원 어레이에 포함된 모든 항목의 위치는 행과 열 인덱스를 조합해서 지정된다.
예를 들어, 정수 7의 위치는 1번 행 인덱스와 2번 열 인덱스로 특정된다.

**차원**

차원은 축의 개수로 지정되며, 따라서 `arr_2D`는 행과 열 두 개의 축을 갖는 2차원 어레이다.

In [12]:
arr_2D.ndim

2

**모양**

2차원 어레이의 모양은 행과 열의 개수를 항목으로 갖는, 길이가 2인 튜플이다.
`arr_2D`는 3개의 행과 4개의 열을 갖기에 `(3, 4)` 모양의 어레이다.

In [13]:
arr_2D.shape

(3, 4)

**어레이 객체 자료형**

2차원 어레이의 자료형도 항목 자료형, 모양과 무관하게 `numpy.ndarray`다.

In [14]:
type(arr_2D)

numpy.ndarray

### 연습문제

(1) ...

## 주요 항목 자료형

데이터 분석, 머신러닝, 딥러닝 등에서 사용되는 넘파이 어레이는
거의 대부분 부동소수점, 정수, 그리고 문자열로 구성된다.

### 부동소수점 자료형

부동소수점으로 구성된 `arr_1D`의 `dtype`은 부동소수점 자료형인 `float64`다.

In [23]:
print('arr_1D:', arr_1D)
print("arr_1D dtype:", arr_1D.dtype)

arr_1D: [ 1.      17.      -7.5      3.14     2.71828]
arr_1D dtype: float64


`float64`에서 64는 넘파이 어레이가 각각의 부동소수점을 저장하기 위해 64비트 크기의 메모리 공간을 할당한다는 의미다.
아래 코드는 `arr_1D`가 가리키는 어레이가 메모리상에서 총 40바이트를 사용함을 확인해준다.

In [24]:
print("항목 자료형:", arr_1D.dtype)
print("어레이 크기 (바이트):", arr_1D.nbytes)

항목 자료형: float64
어레이 크기 (바이트): 40


참고로 1바이트는 8비트에 해당한다.
`arr_1D`가 가리키는 어레이는 총 5개의 부동소수점이 포함되고 하나의 부동소수점이 8바이트 공간을 사용하기에,
총 `5 * 8 = 40` 바이트를 어레이가 차지한다.
어레이의 항목 하나가 차지하는 메모리 크기는 `itemsize` 속성에,
어레이에 포함된 항목의 개수는 `size` 속성에 저장되어 `nbytes`를 다음가 같이 계산할 수도 있다.

In [25]:
print("항목 크기 (바이트):", arr_1D.itemsize)
print("항목 수:", arr_1D.size)
print("전체 크기 (바이트):", arr_1D.itemsize * arr_1D.size)

항목 크기 (바이트): 8
항목 수: 5
전체 크기 (바이트): 40


머신러닝, 딥러닝에서 경우에 다루는 빅데이터는 항목의 개수가 수억개 이상인 경우도 있어서
그런 경우엔 메모리 사용량을 줄이기 위해 64비트 형식의 부동소수점 대신에 32비트, 16비트 형식을 사용하기도 한다.
아래 코드는 `arr_1D`를 생성할 때 `dtype`을 지정하는 방식으로 16비트 형식의 부동소수점을 사용하도록 강제한다.

In [26]:
arr_1D_16 = np.array(list_1D, dtype='float16')
arr_1D_16.dtype

dtype('float16')

기존에 생성된 어레이의 `dtype`을 `astype()` 메서드를 이용하여 변경할 수도 있다.
예를 들어, 아래 코드는 64비트가 아닌 8비트 형식의 부동소수점을 사용하도록 강제한다.

In [27]:
arr_1D_16 = arr_1D.astype('float16')

항목에 포함된 부동소수점이 2바이트만으로는 제대로 다뤄지지 않은 경우에는
소수점 이하 특정 자리에서 잘릴 수도 있다.
예를 들어, 5번째 항목이 `2.71828`에서 `2.719`로 소수점 이하 넷째 자리에서 반올림된 형식으로 지정된다.

In [28]:
arr_1D_16

array([ 1.   , 17.   , -7.5  ,  3.14 ,  2.719], dtype=float16)

항목 자료형인 `dtype`은 지정한대로 `float16`으로 확인된다.

In [29]:
arr_1D_16.dtype

dtype('float16')

각 항목이 차지하는 메모리 공간이 4분의 1로 줄었기에 어레이가 차지하는 메모리 공간 또한 4분의 1로 줄어든 10바이트다.

In [30]:
print("항목 크기 (바이트):", arr_1D_16.itemsize)
print("항목 수:", arr_1D_16.size)
print("전체 크기 (바이트):", arr_1D_16.itemsize * arr_1D_16.size)

항목 크기 (바이트): 2
항목 수: 5
전체 크기 (바이트): 10


### 정수 자료형

정수로 구성된 `arr_2D`의 `dtype`은 정수 자료형인 `int64`다.

In [31]:
arr_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
print('arr_2D dtype:', arr_2D.dtype)

arr_2D dtype: int64


`int64`에서 64는 넘파이 어레이가 각각의 정수를 64비트 크기의 공간을 기본 크기로 사용한다는 의미다.
아래 코드는 `arr_2D`가 가리키는 어레이가 메모리상에서 총 96바이트를 사용함을 확인해준다.

In [33]:
arr_2D = np.array(list_2D)

print("항목 자료형:", arr_2D.dtype)
print("어레이 크기 (바이트):", arr_2D.nbytes)

항목 자료형: int64
어레이 크기 (바이트): 96


`arr_2D`가 가리키는 어레이는 총 12개의 정수가 포함되고 하나의 정수가 8바이트 공간을 차지하게
총 `12 * 8 = 96` 바이트를 어레이가 차지한다.

In [34]:
arr_2D.itemsize * arr_2D.size

96

빅데이터를 다룰 때 메모리 사용량을 줄이기 위해 64비트 형식의 정수 대신 32비트, 16비트, 심지어 8비트 형식의 정수를 사용하기도 한다.
아래 코드는 64비트가 아닌 8비트 형식의 정수를 사용하도록 강제한다.

In [35]:
arr_2D_8 = np.array(list_2D, dtype='int8')

또는 기존에 생성된 어레이를 `astype()` 메서드를 이용하여 `dtype`을 변경할 수도 있다.

In [36]:
arr_2D_8 = arr_2D.astype('int8')

항목에 포함된 정수가 최대 12이기에 1바이트만 사용해도 필요한 정수를 다루는 데에 충분하다.
실제로 어레이를 확인해도 겉모습은 동일하다.

In [37]:
arr_2D_8

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)

다만, `dtype`이 달라졌을 뿐이다.

In [38]:
arr_2D_8.dtype

dtype('int8')

각 항목이 차지하는 메모리 공간이 8분의 1로 줄었기에 어레이가 차지하는 메모리 공간 또한 8분의 1로 줄어든 12바이트다.

In [39]:
print("항목 크기 (바이트):", arr_2D_8.itemsize)
print("항목 수:", arr_2D_8.size)
print("전체 크기 (바이트):", arr_2D_8.itemsize * arr_2D_8.size)

항목 크기 (바이트): 1
항목 수: 12
전체 크기 (바이트): 12


### 문자열 자료형

문자열은 기본적으로 유니코드로 처리되며, 크기는 최장 길이의 문자열 항목에 맞춰 결정된다.
예를 들어 아래 코드는 어레이에 포함된 가장 긴 문자열 `'python'` 의 길이가 6이기에
`<U6`가 자료형으로 지정됨을 보여준다.
즉, 어레이에 포함된 모든 문자열의 최대 길이가 6이라는 의미다.

In [40]:
arr_string = np.array(['python', 'data', 'numpy'])
arr_string.dtype

dtype('<U6')

:::{note} 유니코드

유니코드<font size='2'>Unicode</font>는 전 세계의 모든 문자를 하나의 표준 체계로 정의하고 각 문자에 고유한 번호(코드 포인트)를 부여하는 국제 문자 집합 표준이다. UTF-8, UTF-16 등의 다양한 인코딩 방식으로 컴퓨터에 저장된다.
:::

어레이를 생성할 때 `dtype='str'`을 지정하면 모든 항목을 문자열로 변환한다.
예를 들어, 아래 코드는 정수와 부동소수점으로 구성된 리스트의 항목을 모두 문자열로 변환하여
어레이를 생성한다.

In [41]:
numeric_1D_strings = np.array(list_1D, dtype='str')
numeric_1D_strings

array(['1', '17', '-7.5', '3.14', '2.71828'], dtype='<U7')

아래 어레이의 자료형은 `<U7`인데, 문자열 `'2.71828'` 길이가 7로 가장 크기 때문이다.

반면에 아래 코드는 `list_2D`에 포함된 모든 정수를 문자열로 변환하여 2차원 어레이를 생성하며,
`dtype`은 최대 2개의 기호를 사용하는 문자열로 구성되었기에 `'<U2'`로 지정된다.

In [42]:
numeric_2D_strings = np.array(list_2D, dtype='str')
numeric_2D_strings

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['9', '10', '11', '12']], dtype='<U2')

### `object` 자료형

파이썬의 모든 자료형은 `object` 클래스를 상속한다.
즉, 임의의 값의 자료형은 항상 `object` 자료형이 된다.
따라서 넘파이 어레이를 정의할 때 `dtype=object`를 사용하면 
각 항목의 자료형을 그대로 보존하면서 어레이를 생성할 수 있다. 

In [63]:
array_of_object = np.array([1, 'two', 3.0], dtype=object)
array_of_object

array([1, 'two', 3.0], dtype=object)

`object`를 항목 자료형으로 지정하면 여러 자료형을 그대로 유지하면서 하나의 어레이로 다룰 수 있다는 점에서 매우 유용하다.
하지만 `int64`, `float64`, `str` 등 특정 자료형으로 지정한 
경우에 비해 메모리 효율이 낮고 처리 속도가 느려진다는 점은 기억해 두어야 한다.

### 연습문제

(1) ...

## 실전 예제: 붓꽃 데이터셋

붓꽃<font size='2'>Iris</font> 데이터셋은 1936년 통계학자 로날드 피셔<font size='2'>Ronald Fisher</font>에 의해 발표된 고전적인 데이터셋이다.
자동분류 문제를 연구하기 위해 수집되었으며, 세토사<font size='2'>Setosa</font>, 
버시컬러<font size='2'>Versicolor</font>, 
버지니카<font size='2'>Verginica</font> 등 
붓꽃의 세 가지 품종에 대해 꽃잎 길이와 너비, 꽃받침 길이와 너비 정보를 포함한 150개의 샘플로 구성되어 있다.

이 데이터셋은 데이터 분석과 기계학습 분야에서 가장 널리 사용되는 예제 데이터셋이다.

:::{note} 데이터 샘플 vs. 데이터셋

데이터 샘플<font size='2'>data</font>는 개별 정보 또는 값 자체를 의미하고, 
데이터셋<font size='2'>dataset</font>은 특정 목적을 위해 수집되고 구조화된 데이터 샘플의 모음을 의미한다.

| 구분 | 데이터 샘플 | 데이터셋 |
|------|--------|----------|
| 정의 | 개별 사실, 값, 관찰 결과 | 특정 목적으로 수집된 데이터의 집합 |
| 예시 | 175cm, 70kg (한 사람의 키, 체중) | 1,000명의 키, 몸무게, 나이 정보 |
| 구조 | 단일 값 | 표, 엑셀 파일 등 체계적으로 정리된 구조 |

### 데이터셋 저장소

데이터셋 저장소는 데이터 분석과 머신러닝 학습을 위해 수집하고 정리한 데이터셋들을 보관하는 공간이다.
본 강의노트는 실전에서 구한 데이터셋을 아래 저장소에서 다운로드하여 데이터 과학의 기초 개념을 소개하는
예제 위주로 구성된다.

In [4]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

### CSV 파일

CSV 파일은 Comma-Separated Values의 약자로, 데이터를 쉼표로 구분하여 저장하는 단순한 텍스트 형식의 파일이며 확장자는 .csv이다. 각 행은 줄바꿈으로 구분되고, 행 안의 데이터는 쉼표로 나뉘어 엑셀과 같은 표 형태로 표현된다. 따라서 모든 행은 동일한 개수의 쉼표를 가지며, 행별 데이터 수가 일정하고, 
행별로 동일한 열에 위치한 값들은 동일한 특성을 공유한다.

CSV는 주로 간단한 표 데이터를 저장하고 공유하는 데 적합한 파일 형식이다. 구조가 단순하고 호환성이 뛰어나기 때문에 엑셀과 파이썬을 비롯한 다양한 편집기와 프로그래밍 언어에서 CSV 파일을 다루는 기능을 폭넓게 제공한다.

**`iris_dataset.csv` 파일**

`iris_dataset.csv` 파일에 붓꽃 데이터 150개가 아래 형식으로 저장되어 있다.
각 샘플은 꽃받침 길이와 폭, 꽃잎 길이와 폭 등 4개의 수치형 특성과 해당 샘플의 품종을 나타내는 문자열을 포함하고 있다.

:::{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/iris_csv.png
:width: 80%
:align: center
:::

**헤더**

파일 첫행의 `sepal.length,sepal.width,petal.length,petal.width,variety`은 각각의 열에 포함된 데이터의 종류를
알려주는 **헤더**<font size='2'>header</font>다.
헤더는 열별 데이터셋을 대변하는 이름이며, 변수, 변인, 특성 등으로 불린다.
통계학 분야에서는 변수 또는 변인이, 데이터 분석과 머신러닝 분야에서는 특성이란 표현이 선호된다.

붓꽃 데이터셋에 포함된 5개 특성은 다음과 같다.

| 영어 특성명 | 한글 특성명 |
|------|------|
| sepal.length | 꽃받침 길이 |
| sepal.width | 꽃받침 폭 |
| petal.length | 꽃잎 길이 |
| petal.width | 꽃잎 폭 |
| variety | 품종 |

:::{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/iris_petal-sepal.png
:width: 70%
:align: center
:::

### 1차원 어레이로 불러오기

`np.loadtxt()` 함수는 지정된 데이터 저장소나 폴더의 CSV 파일 등 텍스트 파일에 포함된 데이터를 불러와 넘파이 어레이 객체로 반환한다. 
이때 구분자(`delimiter`), 건너뛸 행(`skiprows`), 불러올 열(`usecols`), 항목 자료형(`dtype`) 등의 키워드 인자를
지정하여 원하는 데이터만 원하는 형식으로 선택적으로 불러올 수 있다.  

아래 코드에서는 `iris_dataset.csv` 파일을 읽어올 때 첫행인 헤더를 건너뛰고,
`usecols=0`키워드 인자를 지정하여 0번 열, 즉 꽃받침 길이 데이터가 포함된 열만 1차원 어레이로 가져온다.

In [45]:
iris_sepal_length = np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, dtype='float16', usecols=0)
iris_sepal_length

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9], dtype=float16)

반면에 아래 코드는 4번 열, 즉 꽃잎 너비 데이터를 담은 열만 1차원 어레이로 불러온다.

In [46]:
iris_variety = np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, dtype=str, usecols=4)
iris_variety

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

각 변수가 가리키는 값을 확인하면 `shape`이 `(150,)`, 즉 150개의 항목을 갖는 1차원 어레이라고 알려준다.
차원은 모양을 가리키는 튜플의 길이가 1인 것으로 확인된다.

In [47]:
iris_sepal_length.shape

(150,)

In [48]:
iris_variety.shape

(150,)

실제로 두 어레이의 `ndim` 속성을 확인하면 차원이 1로 확인된다.

In [49]:
iris_sepal_length.ndim

1

In [50]:
iris_variety.ndim

1

반면에 두 1차원 어레이의 항목 자료형은 서로 다르다.

In [51]:
iris_sepal_length.dtype

dtype('float16')

In [52]:
iris_variety.dtype

dtype('<U10')

### 2차원 어레이로 불러오기

**수치형 특성들만 2차원 어레이로 불러오기**

붓꽃 샘플별로 품종을 제외한 나머지 네 개의 특성으로 구성된 데이터만 불러오기 위해
`usecols=(0, 1, 2, 3)`을 지정한다.
즉, 0번 열부터 3번 열까지만 대상으로 `np.loadtxt()` 함수를 적용한다.
네 열에 포함된 데이터가 모두 부동소수점이기에 생성된 어레이의 항목 자료형은
`float64`로 자동 지정된다.

In [5]:
iris_features = np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, usecols=(0, 1, 2, 3))
iris_features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

아래 코드는 `iris_features`가 가리키는 어레이의 모양, 항목 자료형, 차원을 확인해준다.

In [10]:
print('모양:', iris_features.shape)
print('항목 자료형:', iris_features.dtype)
print('차원:', iris_features.ndim)

모양: (150, 4)
항목 자료형: float64
차원: 2


**품종 데이터까지 2차원 어레이로 불러오기**

품종 특성은 문자열로 구성되어 다른 열의 특성값들과 자료형이 다르다.
따라서 모든 데이터를 함께 넘파이 어레이로 불러오려면 `dtype='object'` 또는 `dtype='str'`로 지정해야 한다.
그러면 모든 값이 문자열로 변환되어 어레이에 포함된다.
모든 열(특성)을 2차원 어레이로 불러오려면 `usecols` 키워드 인자는 굳이 지정하지 않아도 된다.
물론 `usecols=(0, 1, 2, 3, 4)`로 모든 열을 지정해도 된다.

In [13]:
iris_full_object = np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, dtype=object)
iris_full_object

array([['5.1', '3.5', '1.4', '.2', 'Setosa'],
       ['4.9', '3', '1.4', '.2', 'Setosa'],
       ['4.7', '3.2', '1.3', '.2', 'Setosa'],
       ['4.6', '3.1', '1.5', '.2', 'Setosa'],
       ['5', '3.6', '1.4', '.2', 'Setosa'],
       ['5.4', '3.9', '1.7', '.4', 'Setosa'],
       ['4.6', '3.4', '1.4', '.3', 'Setosa'],
       ['5', '3.4', '1.5', '.2', 'Setosa'],
       ['4.4', '2.9', '1.4', '.2', 'Setosa'],
       ['4.9', '3.1', '1.5', '.1', 'Setosa'],
       ['5.4', '3.7', '1.5', '.2', 'Setosa'],
       ['4.8', '3.4', '1.6', '.2', 'Setosa'],
       ['4.8', '3', '1.4', '.1', 'Setosa'],
       ['4.3', '3', '1.1', '.1', 'Setosa'],
       ['5.8', '4', '1.2', '.2', 'Setosa'],
       ['5.7', '4.4', '1.5', '.4', 'Setosa'],
       ['5.4', '3.9', '1.3', '.4', 'Setosa'],
       ['5.1', '3.5', '1.4', '.3', 'Setosa'],
       ['5.7', '3.8', '1.7', '.3', 'Setosa'],
       ['5.1', '3.8', '1.5', '.3', 'Setosa'],
       ['5.4', '3.4', '1.7', '.2', 'Setosa'],
       ['5.1', '3.7', '1.5', '.4', 'Setosa'],


`np.loadtxt()` 함수의 `dtype=object` 키워드 인자를 지정해도 모든 열의 자료형이 문자열로 지정되는
`np.loadtxt()` 함수가 여러 자료형이 포함된 경우 문자열로 모든 값을 변환하여 불러오기 때문이다.
따라서 아래 코드에서처럼 차라리 `dtype='str` 지정하는 것이 자료형을 명확히 한다는 측면에서 보다 좋다.

In [14]:
iris_full_str = np.loadtxt(data_url+"iris.csv", delimiter=',', skiprows=1, dtype='str')
iris_full_str

array([['5.1', '3.5', '1.4', '.2', 'Setosa'],
       ['4.9', '3', '1.4', '.2', 'Setosa'],
       ['4.7', '3.2', '1.3', '.2', 'Setosa'],
       ['4.6', '3.1', '1.5', '.2', 'Setosa'],
       ['5', '3.6', '1.4', '.2', 'Setosa'],
       ['5.4', '3.9', '1.7', '.4', 'Setosa'],
       ['4.6', '3.4', '1.4', '.3', 'Setosa'],
       ['5', '3.4', '1.5', '.2', 'Setosa'],
       ['4.4', '2.9', '1.4', '.2', 'Setosa'],
       ['4.9', '3.1', '1.5', '.1', 'Setosa'],
       ['5.4', '3.7', '1.5', '.2', 'Setosa'],
       ['4.8', '3.4', '1.6', '.2', 'Setosa'],
       ['4.8', '3', '1.4', '.1', 'Setosa'],
       ['4.3', '3', '1.1', '.1', 'Setosa'],
       ['5.8', '4', '1.2', '.2', 'Setosa'],
       ['5.7', '4.4', '1.5', '.4', 'Setosa'],
       ['5.4', '3.9', '1.3', '.4', 'Setosa'],
       ['5.1', '3.5', '1.4', '.3', 'Setosa'],
       ['5.7', '3.8', '1.7', '.3', 'Setosa'],
       ['5.1', '3.8', '1.5', '.3', 'Setosa'],
       ['5.4', '3.4', '1.7', '.2', 'Setosa'],
       ['5.1', '3.7', '1.5', '.4', 'Setosa'],


`dtype='str'`로 지정해서 생성된 어레이의 항목 자료형이 `<U10`인 이유는
항목에 포함된 문자열 중에서 `'Versicolor'`의 길이가 10으로 가장 길기 때문이다.
아래 코드는 `iris_full_str`이 가리키는 어레이의 모양, 항목 자료형, 차원을 확인해준다.

In [15]:
print('모양:', iris_full_str.shape)
print('항목 자료형:', iris_full_str.dtype)
print('차원:', iris_full_str.ndim)

모양: (150, 5)
항목 자료형: <U10
차원: 2


### 연습 문제

(1)

## 어레이 연산

넘파이 어레이 연산은 기본적으로 동일한 모양을 갖는 두 어레이에 대해 항목별로 이루어진다.
즉, 지정된 연산을 동일한 위치의 항목끼리 실행하여 새로운, 동일한 모양의 어레이를 생성한다.

### 사칙연산

동일한 모양의 1차원 어레이 두 개를 이용한다.

In [21]:
arr1 = np.arange(1, 6)
arr1

array([1, 2, 3, 4, 5])

In [22]:
arr2 = np.arange(5, 6, 0.2)
arr2

array([5. , 5.2, 5.4, 5.6, 5.8])

동일한 모양의 두 1차원 어레이에 대한 사칙연산은 항목별로 이뤄지며
최종적으로 동일한 모양의 1차원 어레이가 계산된다.

In [105]:
arr1 + arr2

array([ 6. ,  7.2,  8.4,  9.6, 10.8])

In [106]:
arr1 - arr2

array([-4. , -3.2, -2.4, -1.6, -0.8])

In [107]:
arr1 * arr2

array([ 5. , 10.4, 16.2, 22.4, 29. ])

In [108]:
arr1 / arr2

array([0.2       , 0.38461538, 0.55555556, 0.71428571, 0.86206897])

2차원 어레이 연산도 동일한 방식으로 진행된다.
먼저 예제를 위해 (2, 3) 모양의 2차원 어레이를 두 개를 정의한다.

In [34]:
arr3= np.arange(1, 7).reshape((2, 3)).astype('float16')
arr3

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [35]:
arr4= np.arange(13, 2, -2).reshape((2, 3)).astype('float16')
arr4

array([[13., 11.,  9.],
       [ 7.,  5.,  3.]], dtype=float16)

동일한 모양의 두 2차원 어레이에 대한 사칙연산은 항목별로 이뤄지며
최종적으로 동일한 모양의 2차원 어레이가 계산된다.

In [111]:
arr3 + arr4

array([[14., 13., 12.],
       [11., 10.,  9.]], dtype=float16)

In [112]:
arr3 - arr4

array([[-12.,  -9.,  -6.],
       [ -3.,   0.,   3.]], dtype=float16)

In [113]:
arr3 * arr4

array([[13., 22., 27.],
       [28., 25., 18.]], dtype=float16)

In [114]:
arr3 / arr4

array([[0.0769, 0.1818, 0.3333],
       [0.5713, 1.    , 2.    ]], dtype=float16)

### 어레이와 스칼라 사칙연산

**스칼라**<font size='2'>scala</font>는 하나의 숫자 값을 가리키는 용어이며,
리스트, 어레이 등의 모음 자료형의 값과 대비되는 용도로 사용된다.
임의의 어레이와 숫자의 사칙연산은 어레이의 모든 항목에 지정된 숫자와의 사칙연산을 실행한 결과로 구성된
동일한 모양의 어레이로 계산된다.

In [115]:
arr1

array([1, 2, 3, 4, 5])

In [116]:
arr1 - 2

array([-1,  0,  1,  2,  3])

In [117]:
arr1 / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [118]:
arr3

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [119]:
arr3 + 10

array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float16)

In [120]:
arr3 * 3

array([[ 3.,  6.,  9.],
       [12., 15., 18.]], dtype=float16)

### 비교 연산

모양이 동일한 두 어레이의 값 비교도 항목별로 수행되며,
결과물로 생성되는 어레이는 모든 항목이 `bool` 자료형, 즉 `True` 또는 `False`이다.

In [121]:
arr1 < arr2

array([ True,  True,  True,  True,  True])

In [122]:
arr1 == arr2

array([False, False, False, False, False])

In [123]:
arr3 >= arr4

array([[False, False, False],
       [False,  True,  True]])

In [124]:
arr3 != arr4

array([[ True,  True,  True],
       [ True, False,  True]])

어레이와 스칼라의 비교 연산 또한 어레이와 스칼라의 사칙연산의 경우처럼 항목별로 계산된다.

In [125]:
5.5 < arr2

array([False, False, False,  True,  True])

In [126]:
5.4 == arr2

array([False, False,  True, False, False])

In [127]:
8 >= arr4

array([[False, False, False],
       [ True,  True,  True]])

In [128]:
9 != arr4

array([[ True,  True, False],
       [ True,  True,  True]])

### 논리 연산

**부울 어레이**

어레이 비교 연산의 결과는 `dtype`이 `bool`, 즉 모든 항목이 부울값이다.
이처럼 항목 자료형이 `bool`인 어레이를 부울 어레이라 부른다.

**부울 어레이 논리 연산**

부울 어레이를 대상으로 사용 가능한 논리 연산은 세 가지이다. 
첫째, `~`는 부정(not) 연산자로, `True`를 `False`로, `False`는 `True`로 값을 반전시킨다.
둘째, `&`는 논리곱(and) 연산자로, 두 조건이 모두 참일 때만 참을 반환한다.
셋째, `|`는 논리합(or) 연산자로, 두 조건 중 하나 이상이 참이면 참을 반환한다.
언급된 세 논리 연산자는 어레이의 모든 요소에 대해 항목별로 실행되어 동일한 모양의 부울 어레이를 생성한다.

| 기호 | 기능              |
|------|-------------------|
| `~`  | 부정(not) 연산자  |
| `&`  | 논리곱(and) 연산자 |
| `\|`  | 논리합(or) 연산자 |

:::{warning} 주의사항

파이썬의 기본 논리 연산자인 `and`, `or`, `not` 는 넘파이 어레이 연산에 사용할 수 없으며, 
반드시 `&`, `|`, `~` 기호를 사용해야 한다.
:::

**예제: 부정 연산자**

In [27]:
arr1 * 3 >= arr2

array([False,  True,  True,  True,  True])

In [ ]:
~(arr1 * 3 >= arr2)

array([ True, False, False, False, False])

부울 어레이 논리 연산 표현식을 작성할 때 괄호를 적절하게 사용해야 한다.
그렇지 않으면 오류가 발생하거나 다른 결과가 계산될 가능성이 높아진다.
예를 들어, 아래 코드는 부정 연산자를 비트 연산자로 처리하여 엉뚱한 어레이를 계산한다.

In [28]:
~arr1 * 3 >= arr2

array([False, False, False, False, False])

**예제: 논리곱 연산자**

In [32]:
(arr1 + 3 < arr2) & ~(arr1 * 2 >= arr2)

array([ True,  True, False, False, False])

In [36]:
(arr3 > arr4) & (arr3 <= arr4 * 2)

array([[False, False, False],
       [False, False,  True]])

괄호를 사용하지 않으면 오류가 발생한다.
이유는 비트 연산과 논리 연산이 혼용되어 사용되기 때문이다.

In [37]:
arr1 + 3 < arr2 & ~arr1 * 2 >= arr2

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**예제: 논리합 연산자**

In [44]:
(arr1 < arr2-3) | (arr1 >= arr2)

array([ True,  True, False, False, False])

In [38]:
~(arr3 == 5) | (arr4 == 9)

array([[ True,  True,  True],
       [ True, False,  True]])

역시나 괄호를 적절하게 사용하지 않으면 오류가 발생한다.
괄호를 적절하게 사용하지 않는 경우 발생하는 오류에 대해서는 여기서는 자세하게 설명하지 않는다.

In [45]:
~arr3 == 5 | arr4 == 9

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

### 연습문제

(1) ...

## 실전 예제: 피어슨 아버지-아들 키 데이터셋

피어슨 상관계수로 유명한 영국 통계학자 칼 피어슨<font size='2'>Karl Pearson</font>이 1903년에 실험을 위해 수집한
1,078개의 아버지와 아들의 키(신장)로 구성된 데이터셋을 활용한다.
키가 원래 인치 단위로 작성되었지만 편의를 위해 센티미터 단위로 변환하였으며,
`pearson_dataset.csv` 파일에 아래 형식으로 저장되어 있다.

:::{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/pearson_csv.png
:width: 20%
:align: center
:::

첫행의 `Father,Son`은 각각의 열에 포함된 데이터가 아버지들의 키와 아들의 키임을 알려주는
**헤더**<font size='2'>header</font>다.

### 1차원 어레이로 불러오기

피어슨 아버지-아들 키 데이터셋에서 아버지와 아들의 키 데이터를 구분하여 각각 1차원 어레이로 불러오려 한다.
피어슨 데이터셋은 숫자만으로 구성되었기에 `np.loadtxt()` 함수로 편하게 어레이로 불러올 수 있다.

아래 코드에서는 `pearson_dataset.csv` 파일을 읽어올 때 첫행인 헤더를 건너뛰고, 
첫 번째 열(0번 인덱스 열)은 `fathers` 변수가 가리키는 1차원 어레이로, 
두 번째 열(1번 인덱스 열)은 `sons` 변수가 가리키는 1차원 어레이로 각각 불러온다.

In [46]:
fathers = np.loadtxt(data_url+"pearson_dataset.csv", delimiter=',', skiprows=1, usecols=0)
sons = np.loadtxt(data_url+"pearson_dataset.csv", delimiter=',', skiprows=1, usecols=1)

### 2차원 어레이로 불러오기

아래 코드는 피어슨 아버지-아들 키 데이터셋에서 아버지와 아들의 키 데이터를 함께 2차원 어레이로 불러온다.
`fathers`와 `sons`를 정의할 때와는 다르게 `useccols` 키워드 인자를 지정하지 않는다.

In [47]:
pearson = np.loadtxt(data_url+"pearson_dataset.csv", delimiter=',', skiprows=1)

피어슨 아버지-아들 키 데이터셋은 2개의 열만 포함하기에 `usecols=(0, 1)`로 지정해도 동일한 어레이가 반환된다.

In [48]:
pearson = np.loadtxt(data_url+"pearson_dataset.csv", delimiter=',', skiprows=1, usecols=(0, 1))

불러온 값을 확인하면 `shape`이 `(1078, 2)`, 즉 
1,078개의 행과 2개의 열로 구성된 2차원 어레이라고 알려준다.

In [49]:
pearson

array([[165.1, 151.9],
       [160.8, 160.5],
       [165.1, 160.8],
       ...,
       [182.4, 176. ],
       [179.6, 176. ],
       [178.6, 170.2]], shape=(1078, 2))

`ndim`과 `dtype` 속성을 확인하면 다음과 같다.

In [50]:
print('아버지-아들 키 데이터의 차원:', pearson.ndim)
print('아버지-아들 키 데이터의 항목 자료형:', pearson.dtype)

아버지-아들 키 데이터의 차원: 2
아버지-아들 키 데이터의 항목 자료형: float64


### 연습 문제

(1)

## 인덱싱과 슬라이싱

### 1차원 어레이 인덱싱과 슬라이싱

1차원 어레이의 인덱싱과 슬라이싱은 리스트의 경우와 동일하다.
설명을 위해 아래 1차원 어레이를 활용한다.

In [51]:
arr_1D = np.arange(10)
arr_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- 5번 인덱스 항목 인덱싱. 결과는 스칼라.

In [52]:
arr_1D[5]

np.int64(5)

- 5번부터 8번 인덱스 이전까지의 항목 슬라이싱. 결과는 1차원 어레이.

In [53]:
arr_slice = arr_1D[5:8]
arr_slice

array([5, 6, 7])

### 2차원 어레이 인덱싱

2차원 이상의 다차원 어레이는 리스트의 경우보다 
훨씬 효율적인 인덱싱, 슬라이싱 기능을 제공한다.
설명을 위해 아래 2차원 어레이를 활용한다.

In [54]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**행과 열 인덱스**

2차원 어레이는 행과 열 각 축에 대해 각각의 인덱스를 갖는다.
아래 그림에서 보여지듯이 (3, 3) 모양의 2차원 어레이의 상단부터 아래로 내려오는 순서대로 0, 1, 2를 행 인덱스를,
행렬 왼쪽부터 오른쪽으로 이동하면서 순서대로 0, 1, 2를 열 인덱스로 갖는다.
반면에 각 항목 우측 아래에 표시된 튜플은 각 항목의 좌표에 해당하며, 각 항목이 위치한 행과 열의 인덱스의 조합으로 구성된다.

:::{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/index-2D.png
:width: 40%
:align: center
:::

**행 인덱싱**

2차원 어레이의 특정 행을 대상으로 하는 인덱싱은 리스트의 인덱싱을 방식과 동일하며,
결과는 지정된 행의 항목들로 구성된 1차원 어레이다.

- 0번 행 인덱싱. 결과는 1차원 어레이.

In [55]:
arr_2D[0]

array([1, 2, 3])

- 2번 행 인덱싱. 결과는 1차원 어레이.

In [62]:
arr_2D[2]

array([7, 8, 9])

:::{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/indexing-slicing-2D-2.png
:width: 50%
:align: center
:::

**열 인덱싱**

열을 대상으로 하는 인덱싱은 지정된 열에 위치한 항목들로 구성된 1차원 어레이가 생성된다.
행 인덱싱과는 달리, 행과 열의 인덱스를 동시에 지정해야 하며,
모든 행을 대상한다는 의미에서 전체 행을 슬라이싱하는 의미의 `:` 로 지정한다.

- 0번 열 인덱싱. 결과는 1차원 어레이.

In [66]:
arr_2D[:, 0]

array([1, 4, 7])

- 2번 열 인덱싱. 결과는 1차원 어레이.

In [65]:
arr_2D[:, 2]

array([3, 6, 9])

**행과 열 동시 인덱싱**

몇 번 행의 몇 번 열에 위치한 값을 확인하는 방법을 소개한다.
먼저 아래 코드는 중첩 리스트의 경우처럼 인덱싱을 두 번 연속 적용하는 방식이
동일하게 작동함을 보여준다.

- 0번 행의 2번 열에 위치한 값 인덱싱. 결과는 스칼라.

In [56]:
arr_2D[0][2]

np.int64(3)

하지만 2차원 어레이의 0번 행의 2번 열의 값을 인덱싱 하기 위헤
다음과 같이 축별 인덱스를 활용한 좌표 형식의 인덱스 `(0, 2)`를 활용한
인덱싱이 가능하며, 보다 직관적이면서 효율적이다.

- 0번 행, 2번 열 인덱싱. 결과는 스칼라.

In [58]:
arr_2D[0, 2]

np.int64(3)

참고로 아래 방식은 어레이 고유의 방식이며 리스트에 대해서는 동작하지 않는다.
예를 들어 아래 코드는 중첩 리스트에 대해 동일한 방식을 시도하면 
오류가 발생함을 보여준다.

In [70]:
list_2D = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

list_2D[0, 2]

TypeError: list indices must be integers or slices, not tuple

### 2차원 어레이 슬라이싱

**행 슬라이싱**

2차원 어레이에 대한 행 슬라이싱은 리스트 슬라이싱 방식과 동일하게 작동한다.

- 1번 행 이전까지, 즉 0번 행만 대상으로 슬라이싱. 결과는 2차원 어레이.

In [72]:
arr_2D[:1]

array([[1, 2, 3]])

- 1번 행부터 3번 행 이전까지, 즉 1번 행과 2번 행을 대상으로 슬라이싱. 결과는 2차원 어레이.

In [73]:
arr_2D[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

* 전체 행 슬라이싱. 결과는 2차원 어레이.

In [74]:
arr_2D[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- 다음 방식도 가능

In [75]:
arr_2D[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**열 슬라이싱**

열에 대해서만 슬라이싱을 적용하려면 전체 행을 대상으로 열 슬라이싱을 적용하면 된다.

- 2번 열 이전까지, 즉 0번 열과 1번 열 대상 슬라이싱. 결과는 2차원 어레이.

In [71]:
arr_2D[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

:::{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/indexing-slicing-2D-3.png
:width: 50%
:align: center
:::

**행과 열 동시 슬라이싱**

행과 열을 함께 슬라이싱하려면 행과 열에 대한 슬라이싱을 동시에 지정한다.

* 행 기준 2번 행 이전까지, 열 기준 1번 열부터 끝까지 슬라이싱. 결과는 2차원 어레이.

In [76]:
arr_2D[:2, 1:]

array([[2, 3],
       [5, 6]])

:::{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/indexing-slicing-2D-5.png
:width: 50%
:align: center
:::

**인덱싱과 슬라이싱 동시 적용**

인덱싱과 슬라이싱이 행과 열 각각에 대해 독립적으로 사용될 수 있다.

* 행 기준 1번 행 인덱싱, 열 기준 2번 열 이전까지 슬라이싱. 결과는 1차원 어레이.

In [77]:
arr_2D[1, :2]

array([4, 5])

:::{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/indexing-slicing-2D-4.png
:width: 50%
:align: center
:::

* 행 기준 1번 행부터 2번행까지 슬라이싱, 열 기준 0번 열 인덱싱. 결과는 1차원 어레이.

In [78]:
arr_2D[1:3, 0]

array([4, 7])

**주의사항:**

인덱싱을 적용하는 축은 결과에서 사라지며, 따라서 인덱싱 결과는 기존 어레이보다 차원이 1 줄어든다.
따라서 1차원 어레이에 인덱싱을 적용한 결과는 스칼라이고,
2차원 어레이에 행 인덱싱 또는 열 인덱싱을 적용한 결과는 1차원 어레이다.
만약에 2차원 어레이에 행과 열 인덱싱을 동시에 적용하면 결과는 스칼라가 된다.

따라서 동일한 항목을 얻는 슬라이싱일지라도, 인덱싱을 사용할 때와 아닐 때의 결과물은 다른 모양이 된다.
예를 들어, 아래 두 코드는 동일한 항목을 포함한다.
하지만 인덱싱을 적용한 결과는 1차원 어레이인 반면에,
행과 열 모두 슬라이싱을 적용한 결과는 2차원 어레이다.

- 행 인덱스 적용

In [81]:
arr_2D[1, :2]

array([4, 5])

- 행과 열 슬라이싱 적용

In [82]:
arr_2D[1:2, :2]

array([[4, 5]])

- 행 인덱싱 적용 결과의 모양과 차원

In [85]:
print('모양:', arr_2D[1, :2].shape)
print('차원:', arr_2D[1, :2].ndim)

모양: (2,)
차원: 1


- 행과 열 슬라이싱 적용 결과의 모양과 차원

In [86]:
print('모양:', arr_2D[1:2, :2].shape)
print('차원:', arr_2D[1:2, :2].ndim)

모양: (1, 2)
차원: 2


### 연습문제

(1) 아래 그림은 `arr_6x6`이 가리키는 2차원 어레이를 보여준다.
그림에 색깔별로 표시된 어레이를 슬라이싱을 이용하여 구해보자.

In [113]:
arr_6x6 = np.array([[ 0,  1,  2,  3,  4,  5],
                    [10, 11, 12, 13, 14, 15],
                    [20, 21, 22, 23, 24, 25],
                    [30, 31, 32, 33, 34, 35],
                    [40, 41, 42, 43, 44, 45],
                    [50, 51, 52, 53, 54, 55]])

:::{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/numpy-2darray.png
:width: 40%
:align: center
:::
<p><div style="text-align: center">&lt;그림 출처: <a href="https://scipy-lectures.org/intro/numpy/array_object.html#indexing-and-slicing">Scipy Lecture Notes</a>&gt;</div></p>

가. 빨강색 상자로 표시된 1차원 어레이

답:

0번 행의 3번 열에서 4번 열까지로 구성된 1차원 어레이를 생성한다.

In [114]:
arr_6x6[0, 3:5]

array([3, 4])

나. 파랑색 상자로 표시된 2차원 어레이

답:

2번 열에 위치한 항목들로 구성된 2차원 어레이를 생성하려면 모든 행에 대해 2번 열만 추출하되, 인덱싱이 아닌 슬라이싱을 이용해야 한다.

In [115]:
arr_6x6[:, 2:3]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

2번 열에 대해 인덱싱을 적용하면 다음과 같은 1차원 어레이가 된다.

In [116]:
arr_6x6[:, 2]

array([ 2, 12, 22, 32, 42, 52])

다. 보라색 상자로 감싸진 항목들로 구성된 2차원 어레이

답:

행과 열에 대해 모두 스텝 2를 사용하는 슬라이싱을 적용한다.

In [117]:
arr_6x6[2:5:2, 0::2]

array([[20, 22, 24],
       [40, 42, 44]])

라. 초록색 상자로 표시된 2차원 어레이

답:

4번부터 끝까지의 행과 열로 구성되었기에 콜론을 이용해 슬라이싱한다.

In [118]:
arr_6x6[4:, 4:]

array([[44, 45],
       [54, 55]])

(2) ...

## 뷰 기능과 `copy()` 메서드

주어진 어레이 자체를 수정하지 않으면서 새로운 어레이를 생성하는 것처럼 보이도록 하는 기능을 **뷰**<font size='2'>View</font>라 부른다.
넘파이와 다음 장에서 다룰 판다스의 많은 도구가 뷰 기능을 활용한다.
뷰 기능은 메모리를 효율적으로 활용하도록 하기 위해 고안되었지만 경우에 따라 혼란을 야기하기에
어레이의 `copy()` 메서드를 적절하게 활용할 필요가 있다.
여기서는 어레이 인덱싱과 슬라이싱이 새로운 어레이를 생성하는 게 아니라 기존 어레이에 대해 뷰 기능을 사용한다는 점과
`copy()` 메서드의 활용법을 간단한 사례를 통해 살펴본다.

**인덱싱의 뷰 기능**

넘파이 어레이의 인덱싱과 슬라이싱은 리스트의 경우와 다르게,
지정된 인덱스의 위치 또는 구간에 해당하는 어레이를 새로 생성하지 않으면서 구간의 정보를 활용한다.
예를 들어, 아래 코드에서 `arr_6x6_indexing`의 항목을 변경하면 변경된 항목에 대응하는 기존 `arr_6x6`의 항목도 함께 달라진다.
즉, 인덱싱과 슬라이싱이 새로운 어레이를 생성하는 것이 아니라 기존 어레이의 행과 열 인덱스 정보만 활용해서
마치 새로운 어레이를 생성하는 것처럼 보이게 할 뿐이다.

In [128]:
arr_6x6 = np.array([[ 0,  1,  2,  3,  4,  5],
                    [10, 11, 12, 13, 14, 15],
                    [20, 21, 22, 23, 24, 25],
                    [30, 31, 32, 33, 34, 35],
                    [40, 41, 42, 43, 44, 45],
                    [50, 51, 52, 53, 54, 55]])

- `arr_6x6` 2차원 어레이의 1번 행 인덱싱. 결과는 (6,) 모양의 1차원 어레이

In [129]:
arr_6x6_indexing = arr_6x6[1]
arr_6x6_indexing

array([10, 11, 12, 13, 14, 15])

- `arr_6x6_indexing` 1차원 어레이의 0번 인덱스의 항목을 10에서 999로 대체.

In [130]:
arr_6x6_indexing[0] = 999
arr_6x6_indexing

array([999,  11,  12,  13,  14,  15])

- 기존 `arr_6x6` 2차원 어레이의 1번 행, 0번 열의 값이 999로 대체되었음을 확인.

In [131]:
arr_6x6

array([[  0,   1,   2,   3,   4,   5],
       [999,  11,  12,  13,  14,  15],
       [ 20,  21,  22,  23,  24,  25],
       [ 30,  31,  32,  33,  34,  35],
       [ 40,  41,  42,  43,  44,  45],
       [ 50,  51,  52,  53,  54,  55]])

### 슬라이싱의 뷰 기능

아래 코드에서 `arr_6x6_slicing`의 항목을 변경하면 변경된 항목에 대응하는 기존 `arr_6x6`의 항목도 함께 달라진다.
즉, 슬라이싱 또한 새로운 어레이를 생성하는 것이 아니라 기존 어레이의 행과 열 인덱스 정보만 활용해서 
마치 새로운 어레이를 생성하는 것처럼 보이게 할 뿐이다.

- `arr_6x6` 2차원 어레이에 대한 행과 열 모두 1번부터 3번까지만 슬라이싱 적용. 결과는 (3, 3) 모양의 2차원 어레이

In [132]:
arr_6x6_slicing = arr_6x6[1:4, 1:4]
arr_6x6_slicing

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

- 슬라이싱으로 생성된 2차원 어레이의 0번 행, 1번 열의 항목을 12에서 3450으로 대체.

In [133]:
arr_6x6_slicing[0, 1] = 3450
arr_6x6_slicing

array([[  11, 3450,   13],
       [  21,   22,   23],
       [  31,   32,   33]])

- 기존 `arr_6x6` 어레이의 1번 행, 2번 열의 항목이 12에서 3450으로 대체되었음 확인.

In [134]:
arr_6x6

array([[   0,    1,    2,    3,    4,    5],
       [ 999,   11, 3450,   13,   14,   15],
       [  20,   21,   22,   23,   24,   25],
       [  30,   31,   32,   33,   34,   35],
       [  40,   41,   42,   43,   44,   45],
       [  50,   51,   52,   53,   54,   55]])

### `copy()` 메서드

인덱싱과 슬라이싱 결과가 기존 어레이와 독립된 새롭게 생성된 어레이가 되도록 하려면 `copy()` 메서드로 사본을 만들어 활용해야 한다.
예를 들어, 아래 코드는 인덱싱 결과의 사본을 생성하면 기존 어레이와 독립된 별도의 어레이로 지정됨을 보여준다.

In [145]:
arr_6x6 = np.array([[ 0,  1,  2,  3,  4,  5],
                    [10, 11, 12, 13, 14, 15],
                    [20, 21, 22, 23, 24, 25],
                    [30, 31, 32, 33, 34, 35],
                    [40, 41, 42, 43, 44, 45],
                    [50, 51, 52, 53, 54, 55]])

In [146]:
arr_6x6_indexing_copy = arr_6x6[2].copy()
arr_6x6_indexing_copy

array([20, 21, 22, 23, 24, 25])

`arr_6x6_indexing_copy`를 변경해도 `arr_6x6`은 영향받지 않는다.

In [147]:
arr_6x6_indexing_copy[1] = 999
arr_6x6_indexing_copy

array([ 20, 999,  22,  23,  24,  25])

In [148]:
arr_6x6

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

아래 코드는 슬라이싱의 사본도 기존 어레이와 독립된 어레이 객체로 생성된다.

In [149]:
arr_6x6_slicing_copy = arr_6x6[1:4, 1:4].copy()
arr_6x6_slicing_copy[0, 1] = 3450
arr_6x6_slicing_copy
arr_6x6

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

### 연습 문제

(1)