(ch-numpy-array)=
# 넘파이 어레이

넘파이<font size='2'>numpy</font>는 NUMerical PYthon의 줄임말이며,
파이썬 데이터 사이언스에서 가장 유용하게 활용되는 도구를 제공하는 라이브러리다.
넘파이가 제공하는 핵심 요소는 효율적으로 데이터를 저장하고 관리하는 1차원, 2차원, 3차원 등 다차원 어레이(배열)와
메모리 효율적이며 빠른 어레이 연산이다.

**기본 설정**

`numpy` 라이브러리는 관습적으로 별칭 `np`로 불러온다.

In [36]:
import numpy as np

**데이터셋 저장소**

In [44]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

## 다차원 어레이

넘파이 어레이는 리스트 자료형처럼 많은 데이터를 하나의 객체로 묶어 다루는 모음 자료형이며,
데이터 분석, 머신러닝, 딥러닝 등 다량의 데이터로 구성된 데이터셋을
처리할 때 일반적으로 활용된다.
아래 표에 리스트와 넘파이 어레이의 차이점을 정리하였다.

| 특성 | 리스트 | 넘파이 어레이 |
|------|--------|---------------|
| 데이터 저장 | 여러 데이터를 묶어 관리 | 여러 데이터를 묶어 관리 |
| 객체 속성 | 없음. 값만 저장 | 값과 함께 데이터 저장 형식의 모양, 차원, 항목 자료형 등 객체의 메타 데이터를 속성으로 저장 |
| 메서드 | 기본 메서드 제공 | 데이터 과학에 유용한 많은 메서드 제공 |
| 자료형 제약 | 서로 다른 자료형 혼용 가능 | 모든 항목이 동일한 자료형으로 통일되어야 함 |
| 차원 | 차원 개념 없지만 중첩 리스트 지원 | 1차원, 2차원, 3차원, 4차원 등 다차원 구조 지원 |

여기서는 가장 많이 활용되는 1차원과 2차원 어레이의 사용법을 소개한다.

### 1차원 어레이

1차원 어레이는 중첩이 없는 리스트와 동일한 모양을 가지며, 리스트 등에 `np.array()` 함수를 적용하여 생성할 수 있다.
1차원 어레이는 **벡터**<font size='2'>vector</font>로도 불린다.

In [60]:
list_1D = [1, 17, -7.5, 3.14, 2.71828]
arr_1D = np.array(list_1D)

`arr_1D`는 `list_1D` 변수가 가리키는 리스트의 모든 항목을 동일한 순서대로 나열된 항목으로 갖는 1차원 어레이다.

In [62]:
arr_1D

array([ 1.     , 17.     , -7.5    ,  3.14   ,  2.71828])

**항목 자료형**

리스트의 경우 임의의 자료형이 섞인 항목들을 가질 수 있지만
어레이는 통일된 자료형을 요구한다.
따라서 위 결과를 보면 정수 자료형과 부동소수점 자료형을 통일하여 모든 항목을 부동소수점으로 변환하였다.
어레이 항목들의 통일된 자료형은 `dtype` 속성이 가리킨다.

In [63]:
arr_1D.dtype

dtype('float64')

**축**

1차원 어레이의 항목을 리스트처럼 왼쪽에서 오른쪽으로 하나의 방향으로만 이동하면서 확인할 수 있다는 의미에서
1차원 어레이는 한 개의 **축**<font size='2'>axis</font>을 갖는다고 말한다.

**차원**

어레이는 자신에 대한 정보도 객체 내부에 저장한다.
예를 들어, 어레이 자신의 차원은 `ndim` 속성에 할당되어 있다.

In [42]:
arr_1D.ndim

1

**모양**

어레이의 모양은 `shape` 속성에 튜플 자료형으로 저장되어 있다.
1차원 어레이의 모양은 길이가 1인 튜플이며, 튜플의 유일한 항목은 1차원 어레이에 포함된 항목의 개수다.

In [43]:
arr_1D.shape

(5,)

:::{note} 쉼표의 중요성

길이가 1인 튜플은 `(5,)`처럼 반드시 쉼표가 포함되어 있음에 주의한다.
반면에 `(5)`는 그냥 정수 `5`와 동일하다. 즉, 튜플이 아닌 `int` 자료형이다.
:::

**어레이 객체 자료형**

넘파이 어레이 객체의 자료형은 항목 자료형, 차원, 모양과 상관없이 항상 `numpy.ndarray`다.

In [ ]:
type(arr_1D)

numpy.ndarray

### `np.arange()` 함수

`np.arange()` 함수는 `range()` 함수와 매우 유사한 기능을 갖지만, 리스트가 아닌 넘파이 어레이를 반환한다.
예를 들어, 아래 코드는 0부터 9 사이의 정수로 구성된 1차원 어레이를 생성한다.

In [64]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`range()` 함수와의 가장 큰 차이점은 부동소수점을 스텝으로 사용할 수도 있으며,
그러면 부동소수점으로 구성된 1차원 어레이가 생성된다.

예를 들어 아래 코드는 0부터 1까지 스텝 0.1씩 증가시켜 1차원 어레이를 생성한다. 
시작점 0은 어레이의 항목이 되지만, 오른쪽 끝값인 1은 어레이의 항목이 아님에 유의한다.
왜냐하면 `range()` 함수와 동일하게 스텝은 1보다 작은 동안만 적용되기 때문이다.

In [65]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### 2차원 어레이

2차원 어레이의 모든 항목은 동일한 크기의 1차원 어레이어야 한다. 따라서 동일한 길이의 리스트를 항목으로 갖는 중첩 리스트를 2차원 어레이로 변환할 수 있다. 아래 코드는 길이가 4인 두 개의 리스트를 항목으로 갖는 중첩 리스트 `list_2D`를 2차원 어레이 `arr_2D`로 변환한다.

In [66]:
list_2D = [[1, 2, 3, 4],
           [5, 6, 7, 8],
           [9, 10, 11, 12]]
arr_2D = np.array(list_2D)

arr_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**축과 행렬**

2차원 어레이는 **행**<font size='2'>row</font>과 **열**<font size='2'>column</font>
두 개의 축을 가지며, 행은 0번 축, 열은 1번 축이라 부르기도 한다. 
행과 열을 갖는다는 의미에서 **행렬**<font size='2'>matrix</font>로 불린다.
예를 들어, `arr_2D`는 3개의 행과 4개의 열을 갖는 아래 행렬에 대응한다.

$$
\begin{bmatrix}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8\\
9 & 10 & 11 & 12
\end{bmatrix}
$$

**차원**

`arr_2D`는 행과 열 두 개의 축을 갖는 2차원 어레이다.

In [67]:
arr_2D.ndim

2

**모양**

2차원 어레이의 모양은 행과 열의 개수를 항목으로 갖는, 길이가 2인 튜플이다.
`arr_2D`는 3개의 행과 4개의 열을 갖기에 `(3, 4)` 모양의 어레이다.

In [68]:
arr_2D.shape

(3, 4)

**어레이 객체 자료형**

2차원 어레이의 자료형도 항목 자료형, 모양과 무관하게 `numpy.ndarray`다.

In [69]:
type(arr_2D)

numpy.ndarray

### 넘파이 어레이 주요 항목 자료형

**정수 자료형**

반면에 `arr_2D`의 `ndim`은 64비트 형식의 정수 자료형인 `int64`다.
이유는 어레이 생성에 사용된 `data_2D` 리스트에 정수만 포함되었기 때문이다.

In [ ]:
arr_2D.dtype

dtype('int64')

파이썬은 기본적으로 정수와 부동소수점을 64비트로 처리하지만,
어레이 객체는 필요에 따라 `astype()` 메서드를 이용하여 32비트, 16비트, 8비트 형식으로
`ndim` 속성을 지정할 수 있다.

예를 들어, 아래 코드는 `astype()` 메서드를 이용해 16비트 형식의 부동소수점으로 항목들의 자료형을 지정한다. 소수점 이하의 자릿수를 줄이므로 메모리 사용량을 절약하는 데에 사용되곤 한다.

In [ ]:
arr_1D = np.array(data_1D).astype('float16')
arr_1D.dtype

dtype('float16')

아래 코드는 16비트 형식의 정수로 구성된 2차원 어레이를 생성한다.

In [ ]:
arr_2D = np.array(data_2D).astype('int16')
arr_2D.dtype

dtype('int16')

**문자열 자료형**

문자열은 기본적으로 유니코드로 처리되며,크기는 최장 길이의 문자열 항목에 맞춰 결정된다.
예를 들어 아래 코드는 어레이에 포함된 가장 긴 문자열 `'python'` 의 길이가 6이기에
`<U6`가 자료형으로 지정됨을 보여준다.

In [ ]:
arr_string = np.array(['python', 'data'])
arr_string.dtype

dtype('<U6')

반면에 아래 어레이의 자료형은 `<U4`인데, 문자열 `'1.25'`가 길이가 가장 긴 항목이기 때문이다.

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'])
numeric_strings.dtype

dtype('<U4')

### 실전 예제 - 피어슨  데이터셋

피어슨<font size='2'>Pearson</font>이 1903년에 실험을 위해 수집한
아버지와 아들의 키(신장)로 구성된 데이터를 활용한다.
키가 원래 인치 단위로 작성된 데이터이었지만 편의를 위해 센티미터 단위로 변환하였다.
`pearson_dataset.csv` 파일에 아버지와 아들의 신장 데이터 1,078개가 아래 형식으로 저장되어 있다.

```{image} https://raw.githubusercontent.com/codingalzi/code-workout-datasci/master/images/pearson_csv.png
:width: 20%
:align: center

:::{note} csv 파일

CSV 파일은 Comma-Separated Values의 약자로, 데이터를 쉼표로 구분하여 저장하는 단순한 텍스트 형식의 파일이며, 파일 확장자는 csv이다.
각 행은 줄바꿈으로 구분되고, 각 행에 포함된 데이터는 쉼표로 구분되어 엑셀의 표 형태로 데이터를 표현한다.
즉, 각 행은 동일한 개수의 쉼표를 가진다. 
즉 행별 데이터 수가 동일하며, 쉼표에 의해 열이 나뉘고, 동일한 열의 데이터는 같은 특성을 나타낸다. 
CSV는 주로 간단한 표 데이터를 저장하고 공유하는 데 적합한 파일 형식으로 활용된다.
CSV 파일은 구조가 단순하고 호환성이 뛰어나 엑셀과 파이썬을 포함하여 많은 편집기와 프로그래밍 언어가 CSV 파일을 다루는 다양한 기능을 제공한다.
:::

아래 코드는 피어슨 데이터셋에서 아버지와 아들의 키 데이터를 따로따로 1차원 어레이로 불러온다.

In [ ]:
fathers = np.loadtxt(data_url+"pearson_dataset.csv", delimiter=',', skiprows=1, usecols=0)
sons = np.loadtxt(data_url+"pearson_dataset.csv", delimiter=',', skiprows=1, usecols=1)

In [ ]:
fathers

array([165.1, 160.8, 165.1, ..., 182.4, 179.6, 178.6], shape=(1078,))

In [ ]:
sons

array([151.9, 160.5, 160.8, ..., 176. , 176. , 170.2], shape=(1078,))

`fathers`와 `sons` 변수가 가리키는 각각의 1차원 어레이의 차원과 모양은 동일하다.

In [ ]:
print('아버지 키 데이터의 차원:', fathers.ndim)
print('아버지 키 데이터의 모양:', fathers.shape)

아버지 키 데이터의 차원: 1
아버지 키 데이터의 모양: (1078,)


In [ ]:
print('아들 키 데이터의 차원:', sons.ndim)
print('아들 키 데이터의 모양:', sons.shape)

아들 키 데이터의 차원: 1
아들 키 데이터의 모양: (1078,)


## 어레이 연산

넘파이 어레이 연산은 기본적으로 항목별로 이루어진다.
즉, 지정된 연산을 동일한 위치의 항목끼리 실행하여 새로운, 동일한 모양의 어레이를 생성한다.

### 1차원 어레이 사칙연산

모양이 동일한 아래 1차원 어레이 두 개를 이용하여
어레이 사칙연산의 작동법을 보여준다.

In [22]:
arr1 = np.array([1.0, 2, 3.2])
arr2 = np.array([1, 2, 3])

In [23]:
arr1 + arr2

array([2. , 4. , 6.2])

In [24]:
arr1 - arr2

array([0. , 0. , 0.2])

In [25]:
arr1 * arr2

array([1. , 4. , 9.6])

In [26]:
arr1 / arr2

array([1.        , 1.        , 1.06666667])

### 2차원 어레이 사칙연산

2차원 어레이 연산도 동일한 방식으로 진행된다.

In [27]:
arr3= np.array([[1., 2., 3.], [4., 5., 6.]])
arr3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
arr4 = np.array([[3., 2., 1.], [4., 2., 12.]])
arr4

array([[ 3.,  2.,  1.],
       [ 4.,  2., 12.]])

In [29]:
arr3 + arr4

array([[ 4.,  4.,  4.],
       [ 8.,  7., 18.]])

In [30]:
arr3 - arr4

array([[-2.,  0.,  2.],
       [ 0.,  3., -6.]])

In [31]:
arr3 * arr4

array([[ 3.,  4.,  3.],
       [16., 10., 72.]])

In [32]:
arr3 / arr4

array([[0.33333333, 1.        , 3.        ],
       [1.        , 2.5       , 0.5       ]])

### 비교 연산

모양이 동일한 두 어레이의 값 비교도 항목별로 수행되며,
결과물로 생성되는 어레이는 모든 항목이 `bool` 자료형, 즉 `True` 또는 `False`이다.

In [33]:
arr4 > arr3

array([[ True, False, False],
       [False, False,  True]])

In [34]:
arr4 <= arr3

array([[False,  True,  True],
       [ True,  True, False]])

In [35]:
arr3 != arr4

array([[ True, False,  True],
       [False,  True,  True]])

In [36]:
arr3 == arr3

array([[ True,  True,  True],
       [ True,  True,  True]])

In [37]:
1.2 < arr3

array([[False,  True,  True],
       [ True,  True,  True]])

In [38]:
1.2 >= arr4

array([[False, False,  True],
       [False, False, False]])

### 논리 연산

어레이를 대상으로 사용 가능한 논리 연산은 아래 세 가지이며,
논리 연산 또한 항목별로 실행되어
동일한 모양의 어레이를 생성한다.

```{list-table} 어레이 논리 연산자
:header-rows: 1
:label: array-logical

*   - 기호
    - 기능
*   - `~`
    - 부정(not) 연산자
*   - `&`
    - 논리곱(and) 연산자
*   - `|`
    - 논리합(or) 연산자
```

In [39]:
~(arr3 == arr3)

array([[False, False, False],
       [False, False, False]])

In [40]:
(arr3 == arr3) & (arr4 == arr4)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [41]:
~(arr3 == arr3) | (arr4 == arr4)

array([[ True,  True,  True],
       [ True,  True,  True]])

## 어레이 모양 변형

어레이의 항목을 그대로 유지하면서 모양만 변형시키는 방식과
활용법을 소개한다.

**`reshape()` 메서드**

`reshape()` 메서드는 어레이의 모양을 변형하는데 쓰인다. 단, 전체 항목의 수가 변하지 않도록 모양을 지정해야 한다.
예를 들어, 길이 8인 1차원 어레이는 (4, 2) 모양의 2차원 어레이로 변형할 수 있지만, (4, 3) 모양의 어레이로 변형하려 하면 오류를 발생시킨다.

In [42]:
arr_arange8 = np.arange(8)
arr_arange8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
arr_arange8.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [44]:
arr_arange8.reshape((4, 3))

ValueError: cannot reshape array of size 8 into shape (4,3)

**`-1`의 역할**

어레이의 모양을 지정하는 튜플의 특정 위치에 -1을 사용하면, 그 위치의 값은 어레이의 전체 항목 수와 튜플의 다른 항목에 의해 자동으로 결정된다.
예를 들어, 아래 코드에서 -1은 4로 결정된다. 20개의 항목을 5개의 행을 가진 2차원 어레이로 지정하려면 열의 개수가 4가 되기 때문이다.

In [45]:
arr_arange20 = np.arange(20)
arr_arange20.reshape((5, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [46]:
arr_arange20.reshape((5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

마찬가지로, 아래 코드에서 -1은 5를 의미한다.

In [47]:
arr_arange20.reshape((-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## 브로드캐스팅

**브로드캐스팅**<font size='2'>broadcasting</font>
기능은 모양이 서로 다른 두 어레이가 주어졌을 때 두 모양을 통일시킬 수 있다면 두 어레이의 연산이 가능하도록
도와주는 기능이다.
설명을 위해 하나의 어레이와 하나의 정수의 곱셈이 작동하는 과정을 살펴본다.

In [48]:
arr_623 = np.arange(6).reshape((2,3))
arr_623

array([[0, 1, 2],
       [3, 4, 5]])

위 어레이에 4를 곱한 결과는 다음과 같다.

In [49]:
arr_623 * 4

array([[ 0,  4,  8],
       [12, 16, 20]])

결과가 항목별로 곱해지는 이유는 `arr * 4` 가 아래 어레이의 곱셈과 동일하게 작동하기 때문이다.
즉, 정수 4로 채워진 동일한 모양의 어레이를 먼저 생성한 후에 항목별 곱셈을 진행한 결과와 동일하다.

<div align="center"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/broadcasting14.png?raw=true" style="width:300px;"></div>

이와 같이 어레이의 모양을 확장하여 항목별 연산을 가능하게 해주는 브로드캐스팅 기능은 두 어레이의 모양이 항목별 연산을 일괄적으로 적용시켜도 무방한 경우에는 자동 적용된다.

아래 예제는 (4, 3) 모양의 2차원 어레이와 (3,) 모양의 1차원 어레이의 덧셈을 실행해서 브로드캐스팅 기능이 어떻게 작용하는지를 보여준다. 먼저 1차원 어레이를 (4,1) 모양의 2차원 어레이로 변형한 후, (4,3) 모양의 어레이로 확장시킨다.

In [50]:
arr_arange4_2D = np.array([[0, 0, 0],
                           [1, 1, 1],       
                           [2, 2, 2],
                           [3, 3, 3]])
arr_arange4_2D

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

또다른 어레이는 (3,) 모양으로 생성한 후, 앞의 어레이와 덧셈을 실행해 본다.

In [51]:
arr_arange14 = np.arange(1, 4)
arr_arange14

array([1, 2, 3])

In [52]:
arr_arange4_2D + arr_arange14

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

위 연산이 작동하는 이유는 아래 그림을 통해 이해할 수 있다.

<div align="center"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/broadcasting10.png?raw=true" style="width:400px;"></div>

아래 코드는 (4,3) 모양의 어레이와 (4,1) 모양의 어레이의 덧셈에도 
브로드캐스팅 기능이 마찬가지로 자동 적용됨을 보여준다.

In [53]:
arr_arange15_2D = np.arange(1, 5).reshape((4,1))
arr_arange15_2D

array([[1],
       [2],
       [3],
       [4]])

In [54]:
arr_arange4_2D + arr_arange15_2D

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

아래 그림이 위 연산이 작동하는 이유를 설명한다.

<div align="center"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/broadcasting11.png?raw=true" style="width:400px;"></div>

하지만 (4,3) 모양의 어레이와 (1,4) 모양의 어레이의 항목별 연산은 정의될 수가 없으므로, 브로드캐스팅이 가능하지 않고 오류가 발생한다.

In [55]:
arr_arange15_reshaped = arr_arange15_2D.reshape(1,4)
arr_arange15_reshaped

array([[1, 2, 3, 4]])

In [56]:
arr_arange4_2D + arr_arange15_reshaped

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 

아래 그림이 이유를 설명해준다.

<div align="center"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/broadcasting11a.png?raw=true" style="width:380px;"></div>

<p><div style="text-align: center">&lt;그림 출처: <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html">NumPy: Broadcasting</a>&gt;</div></p>

## 인덱싱과 슬라이싱

**1차원 어레이 인덱싱과 슬라이싱**

1차원 어레이의 인덱싱과 슬라이이싱은 리스트와 거의 동일하다.

In [69]:
arr_1D = np.arange(10)
arr_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr_1D[5]

5

In [71]:
arr_slice = arr_1D[5:8]
arr_slice

array([5, 6, 7])

**슬라이싱의 뷰 기능**

넘파이 어레이의 슬라이싱은 리스트와 다르게,
지정된 구간의 객체를 새로 생성하는 게 아니라 구간의 정보를 활용하기만 한다.
이러한 기능을 **뷰**<font size='2'>view</font>라고 부르는데, 
슬라이싱을 포함하여 넘파이 어레이와 관련된 많은 함수가 뷰 기능을 사용한다.

예를 들어, 아래 코드에서 `arr_slice`의 항목을 변경하면 `arr_1D`의 항목도 함께 달라진다.
즉, 슬라이싱이 새로운 어레이를 생성하는 것이 아님이 확인된다.

In [72]:
arr_slice[1] = 3450
arr_1D

array([   0,    1,    2,    3,    4,    5, 3450,    7,    8,    9])

**`copy()` 메서드**

따라서 슬라이싱할 때, 원본을 그대로 유지하려면 `copy()` 메서드로 사본을 만들어 활용할 것을 권장한다.

In [66]:
arr_slice2 = arr[5:8].copy()
arr_slice2

array([   5, 3450,    7])

`arr_slice2`를 변경해도 `arr`은 영향받지 않는다.

In [67]:
arr_slice2[1] = 12
arr_slice2

array([ 5, 12,  7])

In [68]:
arr

array([   0,    1,    2,    3,    4,    5, 3450,    7,    8,    9])

**2차원 어레이 인덱싱과 슬라이싱**

2차원 이상의 다차원 어레이는 리스트보다 훨씬 다양한 인덱싱, 슬라이싱 기능을 제공한다.

In [73]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

우선 리스트의 인덱싱을 그대로 사용할 수 있다.

In [74]:
arr_2D[0]

array([1, 2, 3])

In [75]:
arr_2D[0][2]

3

하지만 어레이는 다음과 같이 축별 인덱스를 활용한 좌표 형식의 인덱싱도 허용한다.

In [78]:
arr_2D[0, 2]

3

슬라이싱 또한 리스트 슬라이싱 방식을 동일하게 적용할 수 있다.

* 1번 인덱스 이전까지

In [79]:
arr_2D[:1]

array([[1, 2, 3]])

* 2번 인덱스 이전까지

In [80]:
arr_2D[:2]

array([[1, 2, 3],
       [4, 5, 6]])

* 전체 항목 슬라이싱

In [81]:
arr_2D[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

행과 열을 함께 슬라이싱하려면 행과 열에 대한 슬라이싱을 동시에 지정한다.

* 행 기준: 2번 행 이전까지
* 열 기준: 1번 열부터 끝까지

In [82]:
arr_2D[:2, 1:]

array([[2, 3],
       [5, 6]])

<div align="center" border="1px"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/numpy149-1.png" style="width:350px;"></div>

인덱싱과 슬라이싱이 행과 열 각각에 대해 독립적으로 사용될 수 있다.

* 행 기준: 1번 행 인덱싱
* 열 기준: 2번 열 이전까지

In [83]:
arr_2D[1, :2]

array([4, 5])

<div align="center" border="1px"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/numpy149-4.png" style="width:350px;"></div>

**주의사항:**

슬라이싱 결과물의 차원은 기존 어레이의 차원보다 인덱싱을 사용하는 축의 개수만큼 줄어든다. 따라서 동일한 항목을 얻는 슬라이싱일지라도, 인덱싱을 사용할 때와 아닐 때의 결과물은 다른 모양이 된다.
예를 들어, 아래 코드는 0번 축에 대해 인덱싱을 사용하므로, 슬라이싱의 결과물은 1차원 어레이이다.

In [84]:
arr_2D[1, :2]

array([4, 5])

In [85]:
arr_2D[1, :2].shape

(2,)

반면에, 아래 코드는 모든 축에 대해 슬라이싱을 적용하였기에 차원이 그대로 유지된 (1,2) 어레이가 된다.

In [86]:
arr_2D[1:2, :2]

array([[4, 5]])

In [87]:
arr_2D[1:2, :2].shape

(1, 2)

## 예제

### 예제: 붓꽃 데이터셋

아래 링크에 아이리스(붓꽃) 데이터(iris.data)가 저장되어 있다.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [ ]:
iris_full = np.genfromtxt(url, delimiter=',', dtype=str)

In [ ]:
iris_full

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [ ]:
iris_data = np.genfromtxt(url, delimiter=',', dtype=float, usecols=(0,1,2,3))

In [ ]:
iris_data = np.genfromtxt(url, delimiter=',', usecols=(0,1,2,3))

In [ ]:
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

**예제 1**

아래 모양의 2차원 어레이를 지정된 단계를 따라 생성해보자.

```python
array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
```

(1) 먼저 `np.arange()` 함수와 `reshape()` 어레이 메서드만 사용하여, 아래 모양의 어레이를 `arr_e1` 이름으로 생성한다.

```python
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])
```

답:

2차원 어레이의 모양이 (6, 6)이지만 항목이 0에서 35까지의 정수로 구성된다.
따라서 `np.arange(36)`로 1차원 어레이를 만든 다음에 `reshape()` 메서드를 적용한다.

In [88]:
arr_e1 = np.arange(36)
arr_e1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

이제 (6, 6) 모양의 2차원 어레이로 변환한다.

In [89]:
arr_e1 = arr_e1.reshape((6,6))
arr_e1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

또는

In [90]:
arr_e1 = arr_e1.reshape((6,-1))
arr_e1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

한줄 코드로 작성하면 다음과 같다.

In [91]:
arr_e1 = np.arange(36).reshape((6,-1))
arr_e1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

(2) `np.arange()` 함수와 `reshape()` 어레이 메서드만 사용하여 아래 모양의 어레이를 `arr_e2` 라는 이름으로 생성한다.

```python
array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]])
```

답:

2차원 어레이긴 하지만 0, 4, 8, 12, 16, 20으로 구성되었다.
따라서 먼저 해당 항목들로 구성된 1차원 어레이를 생성한다.

In [92]:
arr_e2 = np.arange(0, 21, 4)
arr_e2

array([ 0,  4,  8, 12, 16, 20])

이제 (6,1) 모양의 2차원 어레이로 변환한다.

In [93]:
arr_e2 = arr_e2.reshape((6,1))
arr_e2

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]])

한줄 코드로 작성하면 다음과 같다.

In [94]:
arr_e2 = np.arange(0, 21, 4).reshape((6,1))
arr_e2

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]])

(3) 이제 arr_e1과 arr_e2를 이용하여 아래 모양의 어레이를 생성한다.

```python
array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
```

답:

두 어레이를 더하면 `arr_e2`에 대해 브로드캐스팅이 작동하여 원하는 모양의 어레이가 생성된다.

In [96]:
arr = arr_e1 + arr_e2
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

**예제 2**

아래 그림은 `arr`이 가리키는 2차원 어레이를 보여준다.
그림에 색깔별로 표시된 어레이를 슬라이싱을 이용하여 구해보자.

<div align="center" border="1px"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/numpy-2darray.png" style="width:250px;"></div>

<p><div style="text-align: center">&lt;그림 출처: <a href="https://scipy-lectures.org/intro/numpy/array_object.html#indexing-and-slicing">Scipy Lecture Notes</a>&gt;</div></p>

(1) 빨강색 상자로 표시된 1차원 어레이

답:

0번 행의 3번 열에서 4번 열까지로 구성된 1차원 어레이를 생성한다.

In [97]:
arr[0, 3:5]

array([3, 4])

(2) 파랑색 상자로 표시된 2차원 어레이

답:

2번 열에 위치한 항목들로 구성된 2차원 어레이를 생성하려면 모든 행에 대해 2번 열만 추출하되, 인덱싱이 아닌 슬라이싱을 이용해야 한다.

In [98]:
arr[:, 2:3]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

2번 열에 대해 인덱싱을 적용하면 다음과 같은 1차원 어레이가 된다.

In [99]:
arr[:, 2]

array([ 2, 12, 22, 32, 42, 52])

(3) 보라색 상자로 감싸진 숫자들로 구성된 2차원 어레이

답:

행과 열에 대해 모두 스텝 2를 사용하는 슬라이싱을 적용한다.

In [100]:
arr[2:5:2, 0::2]

array([[20, 22, 24],
       [40, 42, 44]])

(4) 초록색 상자로 표시된 2차원 어레이

답:

4번부터 끝까지의 행과 열로 구성되었기에 콜론을 이용해 슬라이싱한다.

In [101]:
arr[4:, 4:]

array([[44, 45],
       [54, 55]])