# 판다스 시리즈

판다스<font size='2'>Pandas</font>는 넘파이와 함께 데이터 분석에서 가장 많이 활용되는 라이브러리다.
판다스가 제공하는 두 개의 자료형 `Series`와 `DataFrame`은
데이터를 매우 효율적으로 다루는 다양한 기능을 제공한다.

넘파이 어레이는 다차원 수치형 데이터를 처리하는 데에 특화된 반면,
판다스의 시리즈와 데이터프레임은 표<font size='2'>table</font> 형식으로 제공되는 
모든 유형의 2차원 데이터를 다룰 수 있다.

아래 이미지는 Mango, Apple, Banana 세 개의 과일 이름으로 구성된 열과
날짜별 과일 종류별 개수로 구성된 5개의 행으로 구성된 엑셀 표를 보여준다.

<div align="center">
    <img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/excel-fruits.png" width="450">
</div>

판다스 라이브러리의 `Series` 객체는 위 표의 각 열을,
`Dataframe` 객체는 위 표 전체를 효율적으로 다룰 수 있다.

여기서는 먼저 시리즈를, 다음 장에서 데이터프레임을 소개한다.

**기본 설정**

`numpy`와 `pandas` 라이브러리를 각각 `np`와 `pd`로 불러온다.

In [1]:
import numpy as np
import pandas as pd

**데이터셋 저장소**

In [2]:
data_url = 'https://raw.githubusercontent.com/codingalzi/code-workout-datasci/refs/heads/master/data/'

## 시리즈 생성

시리즈는 1차원 어레이와 동일한 구조를 갖는다.
다만 인덱스를 0, 1, 2..가 아닌 원하는 값으로 지정할 수 있다.
시리즈를 생성하기 위해 리스트, 넘파이 1차원 어레이, 사전 등을 이용한다.

**리스트 활용**

리스트 또는 1차원 어레이를 이용하여 간단하게 시리즈를 생성할 수 있다. 
`dtype`은 어레이 항목의 자료형을 가리키는 것처럼 시리즈에 포함된 항목들의 자료형을 의미한다.

아래 코드는 리스트를 이용하여 위 그림의 표의 각 열에 대응하는 시리즈 객체를 생성한다.
시리즈를 정의할 때 사용되는 `name` 매개변수는 시리즈의 이름을 지정한다.
시리즈 이름의 기능은 나중에 데이터프레임을 생성할 때 유용하게 사용된다.

In [3]:
series1 = pd.Series([4, 5, 6, 3, 1], name="Mango")
series2 = pd.Series([5, 4, 3, 0, 2], name="Apple")
series3 = pd.Series([2, 3, 5, 2, 7], name="Banana")

예를 들어 망고 데이터를 담은 `series1`을 확인해보자.

In [4]:
series1

0    4
1    5
2    6
3    3
4    1
Name: Mango, dtype: int64

마치 하나의 열로 구성된 표을 담은 엑셀파일처럼 0부터 시작하는 행 인덱스와 함께 시리즈의 각 항목이 세로로
정렬된 형식으로 보여진다.
행 인덱스는 시리즈를 생성할 때 별도로 지정하지 않으면 0부터 시작하는 정수 인덱스가 사용된다
행 인덱스는 또한 1차원 어레이와 유사한 방식으로 시리즈 인덱싱과 슬라이싱에 활용된다.

시리즈 객체의 자료형은 다음과 같다.

In [5]:
type(series1)

pandas.Series

시리즈는 1차원이다.

In [6]:
series1.ndim

1

**어레이 활용**

넘파이 1차원 어레이를 이용해 동일한 방식으로 시리즈를 생성할 수 있다.

In [7]:
series1 = pd.Series(np.array([4, 5, 6, 3, 1]), name="Mango")
series2 = pd.Series(np.array([5, 4, 3, 0, 2]), name="Apple")
series3 = pd.Series(np.array([2, 3, 5, 2, 7]), name="Banana")

앞서 리스트를 이용한 경우와 동일한 시리즈 객체를 생성한다.
예를 들어 `series2`를 확인해보자.

In [8]:
series2

0    5
1    4
2    3
3    0
4    2
Name: Apple, dtype: int64

**사전 활용**

사전을 이용하여 시리즈를 생성할 수 있다.
사전의 키가 인덱스로 지정되며,
따라서 아래 코드는 이전과 동일한 세 개의 시리즈 객체를 생성한다.

In [9]:
dic1 = {0: 4, 1: 5, 2: 6, 3: 3, 4: 1}
dic2 = {0: 5, 1: 4, 2: 3, 3: 0, 4: 2}
dic3 = {0: 2, 1: 3, 2: 5, 3: 2, 4: 7}

series1 = pd.Series(dic1, name="Mango")
series2 = pd.Series(dic2, name="Apple")
series3 = pd.Series(dic3, name="Banana")

예를 들어 `series3`를 확인해보자.

In [10]:
series3

0    2
1    3
2    5
3    2
4    7
Name: Banana, dtype: int64

그런데 사전의 키를 바꾸면 인덱스가 달라진다.

In [11]:
dic1 = {'첫째': 4, '둘째': 5, '셋째': 6, '넷째': 3, '다섯째': 1}
dic2 = {'첫째': 5, '둘째': 4, '셋째': 3, '넷째': 0, '다섯째': 2}
dic3 = {'첫째': 2, '둘째': 3, '셋째': 5, '넷째': 2, '다섯째': 7}

series1_count = pd.Series(dic1, name="Mango")
series2_count = pd.Series(dic2, name="Apple")
series3_count = pd.Series(dic3, name="Banana")

예를 들어 `series1`을 확인하면 인덱스가 달라졌음이 확인된다.

In [12]:
series1_count

첫째     4
둘째     5
셋째     6
넷째     3
다섯째    1
Name: Mango, dtype: int64

이처럼 넘파이 1차원 어레이와 시리즈는 아래 두 가지 점에서 다르다.

1. 행 인덱스를 원하는 방식으로 지정할 수 있다.
2. 데이터의 특성을 `name`과 같은 객체 속성으로 지정할 수 있다.

### 연습문제

(1) 아래 리스트를 이용하여 시리즈를 생성하시오.
단, `np.nan`은 결측치, 즉 값이 없어서 비어있는 자리를 표현하는 부동소수점 값이다.

In [13]:
aList = [1, 3, 5, 6, 8]

답:

In [14]:
pd.Series(aList)

0    1
1    3
2    5
3    6
4    8
dtype: int64

(2) 아래 코드는 피어스 아버지-아들 키 데이터셋에서 아버지 키만 넘파이 어레이로 불러온 다음에 시리즈로 변환한다.
넘파이 어레이로 불러올 때 `skiprows=1` 키워드 인자를 지정하여 생략한 `'Father'` 헤더 내용은
생성되는 시리즈의 `name` 속성으로 지정한다.

In [15]:
fathers_array = np.loadtxt(data_url+"pearson_dataset.csv", delimiter=',', skiprows=1, usecols=0)
fathers = pd.Series(fathers_array, name="Father")
fathers

0       165.1
1       160.8
2       165.1
3       167.1
4       155.2
        ...  
1073    170.2
1074    181.1
1075    182.4
1076    179.6
1077    178.6
Name: Father, Length: 1078, dtype: float64

반면에 판다스는 CSV, XLSX 파일을 직접 시리즈로 불러오는 API를 제공한다.
판다스의 `read_csv()` 함수를 이용하여 csv 파일의 특정 열을 한 번에 시리즈로 불러오는 코드를 작성하라.

답:

`pd.read_csv()` 함수를 이용하여 CSV 파일의 첫 번째 열만 불러온 후, `.squeeze()` 메서드를 사용하여 1차원 시리즈(Series) 형태로 변환하면 된다.
`'Father'` 헤더 내용이 자동으로 `name` 속성으로 지정됨에 유의한다.

In [16]:
fathers = pd.read_csv(data_url+"pearson_dataset.csv", usecols=[0]).squeeze()
fathers

0       165.1
1       160.8
2       165.1
3       167.1
4       155.2
        ...  
1073    170.2
1074    181.1
1075    182.4
1076    179.6
1077    178.6
Name: Father, Length: 1078, dtype: float64

## 시리즈 속성

시리즈는 넘파이 어레이보다 많은 속성을 객체 자체에 저장한다.

**`index` 속성**

`index` 속성은 행 인덱스로 사용된 값들로 구성된 `Index` 객체를 가리킨다.
자동으로 생성된 정수 인덱스는 `range` 객체와 유사하게 작동하는 `RangeIndex` 객체로 지정된다.
참고로 `RangeIndex` 클래스는 `Index` 클래스의 자식클래스다.

In [17]:
series1.index

RangeIndex(start=0, stop=5, step=1)

정수 인덱스가 아니면 행 인덱스 사용된 값들로 구성된 `Index` 객체로 지정되며,
어레이처럼 `dtype`을 이용하여 인덱스로 사용된 값들의 자료형을 명시한다.

In [18]:
series1_count.index

Index(['첫째', '둘째', '셋째', '넷째', '다섯째'], dtype='str')

`index` 속성을 임의의 값으로 지정할 수 있다.
단, 항목의 개수와 동일한 길이의 리스트를 이용해야 한다.

In [19]:
new_index = ['영', '일', '이', '삼', '사']
series1_count.index = new_index
series1_count

영    4
일    5
이    6
삼    3
사    1
Name: Mango, dtype: int64

시리즈를 정의할 때 `index` 매개변수의 키워드 인자를 이용하여
원하는 행 인덱스를 지정할 수도 있다.
단, 항목의 수와 동일한 길이를 갖는 리스트를 활용해야 한다.

In [20]:
series1 = pd.Series([4, 5, 6, 3, 1], index=new_index, name="Mango")
series1

영    4
일    5
이    6
삼    3
사    1
Name: Mango, dtype: int64

In [21]:
series1.index

Index(['영', '일', '이', '삼', '사'], dtype='str')

**`name` 속성**

시리즈 객체는 두 종류의 `name` 속성을 활용한다.

- 앞서 사용한 시리즈 항목들의 특성을 가리키는 속성
- 시리즈 인덱스에 사용된 값들의 특성을 가리키는 속성

**시리즈 객체의 `name` 속성**

`Series` 객체를 생성할 때, 또는 생성 이후에
`name` 속성에 시리즈에 포함된 데이터를 대변하는 이름을 지정할 수 있다.
아래 코드는 `series2`의 `name` 속성을 
`'Apple'`에서 `'사과'`로 변경한다.

In [22]:
series2.name = "사과"

아래 코드는 시리즈의 이름이 변경되었을 보여준다.

In [23]:
series2

0    5
1    4
2    3
3    0
4    2
Name: 사과, dtype: int64

**시리즈의 인덱스 객체의 `name` 속성**

시리즈의 인덱스 객체도 `name` 속성을 가질 수 있다.
이 속성은 시리즈에 포함된 값들의 이름이 아니라,
행 인덱스로 사용된 값들이 용도를 설명한다.
예를 들어 날짜, 학생 이름, 지역명 등이 행 인덱스로 사용될 때
인덱스의 이름을 각각 `날짜`, `학생`, `지역` 등으로 지정할 수 있다.

In [24]:
series2.index.name = "순번"
series2

순번
0    5
1    4
2    3
3    0
4    2
Name: 사과, dtype: int64

**`values` 속성**

`values` 속성은 시리즈의 항목만으로 구성된 1차원 어레이를 가리킨다.
이처럼 판다스 시리즈는 넘파이 1차원 어레이를 기본 저장장치로 활용한다.

In [25]:
series1.values

array([4, 5, 6, 3, 1])

In [26]:
series2.values

array([5, 4, 3, 0, 2])

In [27]:
series3.values

array([2, 3, 5, 2, 7])

### 연습문제

(1) 아래 사전을 이용하여 각 과일의 가격을 나타내는 시리즈 `prices`를 생성하고자 한다.

가. 시리즈의 이름(`name` 속성)을 `'과일가격'`으로 지정하면서 시리즈를 생성하라. 

In [28]:
fruit_prices = {'사과': 1500, '바나나': 2500, '망고': 4000}

답:

`name="과일가격"` 키워드 인자를 사용하며 시리즈를 다음과 같이 생성한다.

In [29]:
prices = pd.Series(fruit_prices, name="과일가격")
prices

사과     1500
바나나    2500
망고     4000
Name: 과일가격, dtype: int64

나. 생성된 `prices` 시리즈를 활용하여 다음 두 가지 작업을 순서대로 수행하는 코드를 작성하라.

- 행 인덱스가 무엇을 의미하는지 나타내기 위해 인덱스 객체의 이름(`index.name`)을 '과일종류'`로 지정한다.
- 시리즈에 저장된 가격 데이터(항목)만 넘파이 1차원 어레이로 추출하여 확인한다.

답:

- 인덱스 객체의 이름 지정

In [53]:
prices.index.name = "과일종류"
prices

과일종류
사과     1500
바나나    2500
망고     4000
Name: 과일가격, dtype: int64

- 항목(데이터)만 넘파이 1차원 어레이로 추출

In [52]:
prices.values

array([1500, 2500, 4000])

(2) 아래 코드는 4명 학생의 수학 점수를 담은 시리즈 `scores`를 기본 정수 인덱스를 사용하여 생성한다.

In [54]:
scores = pd.Series([85, 92, 78, 90])

생성된 `scores` 시리즈를 활용하여 다음 세 가지 속성을 변경한 후 시리즈 전체를 확인하는 코드를 작성하라.
* 시리즈의 행 인덱스를 `['철수', '영희', '민수', '지민']`으로 변경한다.
* 행 인덱스의 이름(`index.name`)을 `'학생'`으로 지정한다.
* 시리즈의 이름(`name`)을 `'수학점수'`로 지정한다.

답:

시리즈의 `index`, `index.name`, `name` 속성에 새로운 값을 직접 할당하여 속성을 갱신할 수 있다.

In [55]:
scores.index = ['철수', '영희', '민수', '지민']
scores.index.name = '학생'
scores.name = '수학점수'

scores

학생
철수    85
영희    92
민수    78
지민    90
Name: 수학점수, dtype: int64

## 시리즈 인덱싱과 슬라이싱

시리즈의 인덱싱과 슬라이싱은 시리즈 객체의 인덱스가 어떻게 지정되었는가에 따라
넘파이 1차원 어레이와 동일한 방식과 동일하거나 동일하지 않은 두 가지 방식으로 지원된다.

### 시리즈 인덱싱

먼저, 시리즈 인덱싱을 설명한다.
설명을 위해 아래 시리즈를 이용한다.

In [32]:
series4 = pd.Series(np.arange(0, 11, 2.5), index=['A', 'B', 'C', 'D', 'E'])
series4

A     0.0
B     2.5
C     5.0
D     7.5
E    10.0
dtype: float64

아래 코드는 지정된 인덱스를 직접 이용하여 인덱스와 동일한 행에 위치한 항목을 확인하는
방식을 보여준다.

In [33]:
series4['B']

np.float64(2.5)

그런데 사용자가 직접 지정한 인덱스와는 별도로
시리즈 객체는 내부에 0, 1, 2 등 행 순서에 맞는 정수 인덱스를 별도로 저장하며,
이 정수 인덱스를 리스트와 1차원 어레이의 인덱싱과 동일하게 작동하도록 할 수 있다.
대신 아래 코드에서처럼 `시리즈.iloc[정수인덱스]`형식으로 사용되어야 한다.
아래 코드는 `B` 인덱스 행이 둘째 행이기에 정수 인덱스 1을 이용하여
동일한 항목을 확인해준다.

In [34]:
series4.iloc[1]

np.float64(2.5)

반면에 인덱스 `E`에 해당하는 인덱싱은 다음 세 가지 방식으로 가능하다.
-1은 마지막 인덱스를 가리킴에 주의한다.

In [35]:
series4['E']

np.float64(10.0)

In [36]:
series4.iloc[4]

np.float64(10.0)

In [37]:
series4.iloc[-1]

np.float64(10.0)

### 시리즈 슬라이싱

행 위치를 나타내는 정수 인덱스로 슬라이싱할 때는 `iloc[]`를 사용한다.
사용법은 1차원 어레이의 슬라이싱과 사실상 동일하다.
다만 슬라이싱 결과로 다시 시리즈가 생성되며,
인덱스는 슬라이싱 구간에 포함된 인덱스가 그대로 사용된다.

In [38]:
series4.iloc[1:3]

B    2.5
C    5.0
dtype: float64

반면에 정수가 아닌 주어진 인덱스를 이용하는 슬라이싱은 리스트의 슬라이싱과 비슷하지만,
지정된 구간의 양쪽 끝을 모두 포함한다는 점이 다르다.

예를 들어 아래 코드는 3번 인덱스의 행이 `D` 인덱스 행에 해당하지만 그 행까지 포함하여 슬라이싱이 적용된다.

In [39]:
series4['B':'D']

B    2.5
C    5.0
D    7.5
dtype: float64

### 항목 대체

인덱싱과 슬라이싱을 이용하여 지정된 구간의 항목을 한꺼번에 변경할 수 있다.

**인덱싱 활용**

지정된 인덱스 위치의 항목을 다른 값으로 대체한다.

In [40]:
series4 = pd.Series(np.arange(0, 11, 2.5), index=['A', 'B', 'C', 'D', 'E'])
series4['B'] = -5.0
series4

A     0.0
B    -5.0
C     5.0
D     7.5
E    10.0
dtype: float64

In [41]:
series4 = pd.Series(np.arange(0, 11, 2.5), index=['A', 'B', 'C', 'D', 'E'])
series4.iloc[0] = -2.5
series4

A    -2.5
B     2.5
C     5.0
D     7.5
E    10.0
dtype: float64

**슬라이싱 활용**

항목 변경에 사용되는 값은 스칼라, 즉 정수, 부동소수점, 불리언 등의 단일 값이거나,
슬라이싱 구간의 크기와 동일한 리스트, 튜플, 1차원 어레이 등으로 지정된다.
변경값으로 스칼라를 사용하면 지정된 구간의 모든 항목이 지정된 스칼라로 지정되며,
리스트 등이 지정되면 순서에 맞게 항목이 지정된다.

In [42]:
series4 = pd.Series(np.arange(0, 11, 2.5), index=['A', 'B', 'C', 'D', 'E'])
series4.iloc[1:3] = 7.2
series4

A     0.0
B     7.2
C     7.2
D     7.5
E    10.0
dtype: float64

In [43]:
series4 = pd.Series(np.arange(0, 11, 2.5), index=['A', 'B', 'C', 'D', 'E'])
series4['B':'C'] = 5.0
series4

A     0.0
B     5.0
C     5.0
D     7.5
E    10.0
dtype: float64

In [44]:
series4 = pd.Series(np.arange(0, 11, 2.5), index=['A', 'B', 'C', 'D', 'E'])
series4.iloc[1:3] = [1.5, 2.0]
series4

A     0.0
B     1.5
C     2.0
D     7.5
E    10.0
dtype: float64

In [45]:
series4 = pd.Series(np.arange(0, 11, 2.5), index=['A', 'B', 'C', 'D', 'E'])
series4['B':'C'] = np.array([7.2, 5.0])
series4

A     0.0
B     7.2
C     5.0
D     7.5
E    10.0
dtype: float64

In [46]:
x = 1.2345678901234567898765434567890123456789
x

1.2345678901234567

### 연습문제

(1) 아래에는 5일 동안의 최고 기온을 기록한 시리즈 `temps`가 정의되어 있다.

가. 정수 인덱스가 아닌 지정된 인덱스에 기반한 슬라이싱(예: `['화':'목']`)과 
정수 위치를 이용한 슬라이싱(`.iloc`) 두 가지 방식을 모두 사용하여, 
화요일부터 목요일까지의 기온 데이터를 각각 추출하는 코드를 작성하라.

In [47]:
temps = pd.Series([28.5, 30.2, 31.0, 29.5, 27.8], 
                  index=['월', '화', '수', '목', '금'])

답:

- 라벨을 이용한 슬라이싱 ('목' 포함)

In [48]:
temps['화':'목']

화    30.2
수    31.0
목    29.5
dtype: float64

- 정수 위치 인덱스(iloc)를 이용한 슬라이싱

In [49]:
temps.iloc[1:4]

화    30.2
수    31.0
목    29.5
dtype: float64

나. 생성된 `temps` 시리즈 데이터 중에서 수요일과 목요일의 기온 값을 각각 `32.0`과 `30.5`로 한 번에 변경하려고 한다.
슬라이싱을 이용하여 이 두 항목의 값을 리스트 또는 넘파이 어레이로 동시에 갱신하는 코드를 작성하라.

답:

- 일반 인덱스 슬라이싱 방식

In [57]:
temps['수':'목'] = [32.0, 30.5]
temps

월    28.5
화    30.2
수    32.0
목    30.5
금    27.8
dtype: float64

- 정수 인덱스 슬라이싱 방식

In [58]:
temps.iloc[2:4] = [32.0, 30.5]
temps

월    28.5
화    30.2
수    32.0
목    30.5
금    27.8
dtype: float64

(2)